/**
 * Property Tests: CDC Event Buffer
 *
 * Feature: bootstrap-lifecycle-hardening
 * Properties 5, 6, 7, 8
 * **Validates: Requirements 3.1, 3.2, 3.3, 3.4**
 */

import {test} from '../../src/test-helpers/tap.js';
import fc from 'fast-check';
import {
  CDCEventBuffer,
  buildEventIdentity,
} from '../../src/partition/cdc-event-buffer.js';
import {CDC_OPERATION} from '../../src/constants/cdc.js';

/**
 * Generates a valid CDC operation type.
 */
const cdcOperationArb = fc.constantFrom(
  CDC_OPERATION.INSERT,
  CDC_OPERATION.UPDATE,
  CDC_OPERATION.DELETE,
  CDC_OPERATION.UPSERT,
);

/**
 * Generates a CDC event using the 'nodes' table (primary key: node_id).
 * Uses unique node_id + timestamp combinations to control identity.
 */
function cdcEventArb(idSuffix) {
  const idArb = idSuffix !== undefined ?
    fc.constant(`node-${idSuffix}`) :
    fc.stringMatching(/^node-[a-z0-9]{1,8}$/);
  return fc.record({
    tableName: fc.constant('nodes'),
    operation: cdcOperationArb,
    data: idArb.map((id) => ({node_id: id})),
    timestamp: fc.stringMatching(/^\d{13,16}$/),
    sourcePartition: fc.constant('partition-nodes-p1'),
    sourceReplica: fc.constant('partition-nodes-p1-r1'),
  });
}

/**
 * Generates a non-empty array of unique CDC events.
 * Uniqueness is by event identity (tableName:operation:pk:timestamp).
 */
const uniqueEventsArb = fc.array(cdcEventArb(), {
  minLength: 1,
  maxLength: 20,
}).map((events) => {
  const seen = new Set();
  return events.filter((e) => {
    const id = buildEventIdentity(e);
    if (seen.has(id)) return false;
    seen.add(id);
    return true;
  });
}).filter((events) => events.length > 0);

/**
 * Mock logger that captures warn calls.
 */
function createMockLogger() {
  return {
    warns: [],
    warn(msg, data) {
      this.warns.push({msg, data});
    },
    info() {},
    debug() {},
    error() {},
  };
}

/**
 * Model the current internal-table buffering semantics for the nodes table:
 * keep only the latest buffered event per primary key and preserve the
 * position of that latest occurrence.
 * @param {Array<Object>} events
 * @param {number} [capacity=Infinity]
 * @return {Array<Object>}
 */
function modelBufferedNodeEvents(events, capacity = Infinity) {
  const coalesced = [];
  for (const event of events) {
    const nodeId = event?.data?.node_id;
    const existingIndex = coalesced.findIndex((candidate) => {
      return candidate?.data?.node_id === nodeId;
    });
    if (existingIndex !== -1) {
      coalesced.splice(existingIndex, 1);
    }
    coalesced.push(event);
  }

  if (coalesced.length <= capacity) {
    return coalesced;
  }
  return coalesced.slice(coalesced.length - capacity);
}

test(
  'Feature: bootstrap-lifecycle-hardening, ' +
  'Property 5: Buffer captures events with no subscribers',
  async (t) => {
    /**
     * **Validates: Requirements 3.1**
     *
     * *For any* CDC event generated by a partition leader when no CDC
     * subscribers are registered, the CDCEventBuffer SHALL contain that
     * event, and the buffer size SHALL equal the number of events
     * generated (up to capacity).
     */
    t.test(
      'buffer size equals event count up to capacity',
      async () => {
        await fc.assert(
          fc.property(
            uniqueEventsArb,
            fc.integer({min: 1, max: 50}),
            (events, capacity) => {
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({capacity, logger});

              for (const event of events) {
                buffer.buffer(event);
              }

              const expectedSize =
                modelBufferedNodeEvents(events, capacity).length;
              return buffer.size() === expectedSize &&
                buffer.hasEvents() === true;
            },
          ),
          {numRuns: 10},
        );
      },
    );

    t.test(
      'latest event per node is retained when capacity exceeds coalesced size',
      async () => {
        await fc.assert(
          fc.asyncProperty(
            uniqueEventsArb,
            async (events) => {
              const capacity = events.length + 10;
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({capacity, logger});

              for (const event of events) {
                const buffered = buffer.buffer(event);
                if (!buffered) return false;
              }

              const expectedBufferedEvents =
                modelBufferedNodeEvents(events, capacity);
              if (buffer.size() !== expectedBufferedEvents.length) {
                return false;
              }
              const replayed = [];
              await buffer.replay((event) => {
                replayed.push(event);
              });

              if (replayed.length !== expectedBufferedEvents.length) {
                return false;
              }

              for (let i = 0; i < expectedBufferedEvents.length; i++) {
                if (buildEventIdentity(replayed[i]) !==
                    buildEventIdentity(expectedBufferedEvents[i])) {
                  return false;
                }
              }
              return true;
            },
          ),
          {numRuns: 10},
        );
      },
    );
  },
);

test(
  'Feature: bootstrap-lifecycle-hardening, ' +
  'Property 6: Buffer replay preserves generation order',
  async (t) => {
    /**
     * **Validates: Requirements 3.2**
     *
     * *For any* sequence of CDC events buffered in the CDCEventBuffer,
     * replaying the buffer SHALL deliver events to the subscriber in
     * the exact order they were buffered.
     */
    t.test(
      'replay delivers events in buffered order',
      async () => {
        await fc.assert(
          fc.asyncProperty(
            uniqueEventsArb,
            async (events) => {
              const capacity = events.length + 10;
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({capacity, logger});

              for (const event of events) {
                buffer.buffer(event);
              }

              const replayed = [];
              await buffer.replay((event) => {
                replayed.push(event);
              });

              if (replayed.length !== events.length) return false;

              for (let i = 0; i < events.length; i++) {
                const expectedId = buildEventIdentity(events[i]);
                const actualId = buildEventIdentity(replayed[i]);
                if (expectedId !== actualId) return false;
              }
              return true;
            },
          ),
          {numRuns: 10},
        );
      },
    );
  },
);

test(
  'Feature: bootstrap-lifecycle-hardening, ' +
  'Property 7: Buffer overflow drops oldest events',
  async (t) => {
    /**
     * **Validates: Requirements 3.3**
     *
     * *For any* sequence of N CDC events buffered where N exceeds the
     * buffer capacity C, the buffer SHALL contain exactly C events,
     * and those events SHALL be the last C events from the sequence
     * (oldest dropped first).
     */
    t.test(
      'overflow retains last C events and drops oldest',
      async () => {
        await fc.assert(
          fc.asyncProperty(
            fc.integer({min: 1, max: 10}),
            fc.integer({min: 1, max: 20}),
            async (capacity, extraCount) => {
              const totalCount = capacity + extraCount;
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({capacity, logger});

              const allEvents = [];
              for (let i = 0; i < totalCount; i++) {
                const event = {
                  tableName: 'nodes',
                  operation: CDC_OPERATION.INSERT,
                  data: {node_id: `node-${i}`},
                  timestamp: `${1000000000000 + i}`,
                  sourcePartition: 'partition-nodes-p1',
                  sourceReplica: 'partition-nodes-p1-r1',
                };
                allEvents.push(event);
                buffer.buffer(event);
              }

              if (buffer.size() !== capacity) return false;

              const replayed = [];
              await buffer.replay((event) => {
                replayed.push(event);
              });

              const expectedTail = allEvents.slice(
                totalCount - capacity,
              );

              if (replayed.length !== expectedTail.length) return false;

              for (let i = 0; i < expectedTail.length; i++) {
                const expectedId = buildEventIdentity(expectedTail[i]);
                const actualId = buildEventIdentity(replayed[i]);
                if (expectedId !== actualId) return false;
              }
              return true;
            },
          ),
          {numRuns: 10},
        );
      },
    );

    t.test(
      'overflow emits warning log for each dropped event',
      async () => {
        await fc.assert(
          fc.property(
            fc.integer({min: 1, max: 5}),
            fc.integer({min: 1, max: 10}),
            (capacity, extraCount) => {
              const totalCount = capacity + extraCount;
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({capacity, logger});

              for (let i = 0; i < totalCount; i++) {
                const event = {
                  tableName: 'nodes',
                  operation: CDC_OPERATION.INSERT,
                  data: {node_id: `node-${i}`},
                  timestamp: `${1000000000000 + i}`,
                  sourcePartition: 'partition-nodes-p1',
                  sourceReplica: 'partition-nodes-p1-r1',
                };
                buffer.buffer(event);
              }

              return logger.warns.length === extraCount;
            },
          ),
          {numRuns: 10},
        );
      },
    );
  },
);

test(
  'Feature: bootstrap-lifecycle-hardening, ' +
  'Property 8: Buffer replay deduplicates',
  async (t) => {
    /**
     * **Validates: Requirements 3.4**
     *
     * *For any* set of CDC events where some events were both buffered
     * and subsequently delivered through the normal subscription path,
     * replaying the buffer SHALL not deliver events that were already
     * delivered normally. The total delivery count for each unique
     * event SHALL be exactly one.
     */
    t.test(
      'replay skips events already in deliveredIdentities set',
      async () => {
        await fc.assert(
          fc.asyncProperty(
            fc.integer({min: 2, max: 20}),
            fc.float({min: 0, max: 1, noNaN: true}),
            async (eventCount, splitRatio) => {
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({
                capacity: eventCount + 10,
                logger,
              });

              const events = [];
              for (let i = 0; i < eventCount; i++) {
                const event = {
                  tableName: 'nodes',
                  operation: CDC_OPERATION.INSERT,
                  data: {node_id: `node-${i}`},
                  timestamp: `${1000000000000 + i}`,
                  sourcePartition: 'partition-nodes-p1',
                  sourceReplica: 'partition-nodes-p1-r1',
                };
                events.push(event);
                buffer.buffer(event);
              }

              // Mark first N events as already delivered
              const deliveredCount = Math.max(
                1, Math.floor(splitRatio * eventCount),
              );
              const alreadyDelivered = new Set();
              for (let i = 0; i < deliveredCount; i++) {
                alreadyDelivered.add(buildEventIdentity(events[i]));
              }

              const replayed = [];
              await buffer.replay((event) => {
                replayed.push(event);
              }, alreadyDelivered);

              const expectedCount = eventCount - deliveredCount;
              if (replayed.length !== expectedCount) return false;

              // Verify no replayed event was in the delivered set
              const deliveredSnapshot = new Set(
                events.slice(0, deliveredCount)
                  .map((e) => buildEventIdentity(e)),
              );
              for (const event of replayed) {
                const id = buildEventIdentity(event);
                if (deliveredSnapshot.has(id)) return false;
              }

              return true;
            },
          ),
          {numRuns: 10},
        );
      },
    );

    t.test(
      'total delivery count per event is exactly one',
      async () => {
        await fc.assert(
          fc.asyncProperty(
            fc.integer({min: 3, max: 15}),
            fc.integer({min: 0, max: 100}),
            async (eventCount, splitSeed) => {
              const logger = createMockLogger();
              const buffer = new CDCEventBuffer({
                capacity: eventCount + 10,
                logger,
              });

              const events = [];
              for (let i = 0; i < eventCount; i++) {
                const event = {
                  tableName: 'nodes',
                  operation: CDC_OPERATION.INSERT,
                  data: {node_id: `node-${i}`},
                  timestamp: `${1000000000000 + i}`,
                  sourcePartition: 'partition-nodes-p1',
                  sourceReplica: 'partition-nodes-p1-r1',
                };
                events.push(event);
                buffer.buffer(event);
              }

              // Mark a subset as already delivered
              const splitIndex = splitSeed % eventCount;
              const deliveredIds = new Set();
              const deliveryCounts = new Map();

              for (let i = 0; i <= splitIndex; i++) {
                const id = buildEventIdentity(events[i]);
                deliveredIds.add(id);
                deliveryCounts.set(id, 1);
              }

              // Replay with dedup
              await buffer.replay((event) => {
                const id = buildEventIdentity(event);
                const count = deliveryCounts.get(id) || 0;
                deliveryCounts.set(id, count + 1);
              }, deliveredIds);

              // Every event should have been delivered exactly once
              for (const event of events) {
                const id = buildEventIdentity(event);
                if (deliveryCounts.get(id) !== 1) return false;
              }
              return true;
            },
          ),
          {numRuns: 10},
        );
      },
    );
  },
);
