import {COLUMN, TABLES} from '../constants/index.js';
import {RAFT_ROLE} from '../raft/constants.js';
import {LATENCY_TOPOLOGY_MESSAGE_TYPE} from '../topology/latency-topology-constants.js';

const MESSAGE_STATUS = Object.freeze({
  PENDING: 'pending',
  DELIVERED: 'delivered',
  ACKNOWLEDGED: 'acknowledged',
  FAILED: 'failed',
});

const MESSAGE_GROUP_SUBSYSTEM = Object.freeze({
  NAME: 'message-group',
});

const MESSAGE_GROUP_METADATA_TABLE = Object.freeze({
  PARTITIONS: TABLES.PARTITIONS,
  SERVICES: TABLES.SERVICES,
  NODES: TABLES.NODES,
});

const MESSAGE_GROUP_METADATA_SQL = Object.freeze({
  SELECT_PARTITION_BY_ID:
    `SELECT * FROM ${TABLES.PARTITIONS} WHERE ${COLUMN.PARTITION_ID} = ?`,
  SELECT_SERVICE_BY_ID:
    `SELECT * FROM ${TABLES.SERVICES} WHERE ${COLUMN.SERVICE_ID} = ?`,
  SELECT_NODE_BY_ID:
    `SELECT * FROM ${TABLES.NODES} WHERE ${COLUMN.NODE_ID} = ?`,
});

const MESSAGE_GROUP_APPLICATION_MESSAGE_TYPE = Object.freeze({
  LATENCY_CDC_PROPAGATION: LATENCY_TOPOLOGY_MESSAGE_TYPE.CDC_PROPAGATION,
});

const MESSAGE_GROUP_APPLICATION_STATUS = Object.freeze({
  DUPLICATE: 'duplicate',
  RECEIVED: 'received',
  LATENCY_CDC_PROPAGATED: 'latency_cdc_propagated',
});

const MESSAGE_GROUP_APPLICATION_ERROR_MSG = Object.freeze({
  INVALID_LATENCY_CDC_PAYLOAD: 'Invalid latency CDC propagation payload',
});

export {
  MESSAGE_GROUP_APPLICATION_ERROR_MSG,
  MESSAGE_GROUP_APPLICATION_MESSAGE_TYPE,
  MESSAGE_GROUP_APPLICATION_STATUS,
  MESSAGE_GROUP_SUBSYSTEM,
  MESSAGE_STATUS,
  MESSAGE_GROUP_METADATA_TABLE,
  MESSAGE_GROUP_METADATA_SQL,
  RAFT_ROLE,
};
