import {test} from '../../src/test-helpers/tap.js';
import {
  CONTROL_PLANE_READINESS_DIMENSION,
} from '../../src/control-plane/control-plane-readiness-constants.js';
import {
  PRIORITY_RECOVERY_COMPLETION_STATE,
} from '../../src/control-plane/priority-recovery-completion.js';
import {
  PRIORITY_RECOVERY_ADMISSION_DECISION_REASON,
  PRIORITY_RECOVERY_ADMISSION_PARTITION_CLASS,
  PRIORITY_RECOVERY_ADMISSION_SOURCE,
  buildPriorityRecoveryAdmissionPlan,
  buildPriorityRecoveryClosureWitness,
  buildPriorityRecoveryDecisionSnapshot,
  buildPriorityRecoveryDecisionSnapshots,
  buildPriorityRecoveryPublicationContext,
  buildTrackedPriorityRecoveryDecisionSnapshots,
  isPriorityRecoveryEmergencyPartition,
  normalizePriorityRecoveryDispatchPendingDecisionSnapshot,
  PRIORITY_RECOVERY_CLOSURE_RECORD_ID,
  PRIORITY_RECOVERY_CLOSURE_WITNESS_CLASS,
  PRIORITY_RECOVERY_CLOSURE_WITNESS_STATE,
  resolvePriorityRecoveryAdmissionPlanFromPublication,
  resolveTrackedPriorityRecoveryAdmissionPlan,
} from '../../src/control-plane/priority-recovery-snapshot.js';
import {buildPriorityRecoveryObservationSnapshot} from
  '../../src/control-plane/priority-recovery-observation-snapshot.js';
import {
  PRIORITY_RECOVERY_DECISION_SNAPSHOT_EXPECTED,
  buildPriorityRecoveryActuationDecisionInput,
} from '../distributed/harness/__fixtures__/priority-recovery-actuation-contract-fixture.js';
import {
  OPERATION_WORKFLOW_EFFECT_COMMAND_VALUES,
  OPERATION_WORKFLOW_OUTCOME_VALUES,
  OPERATION_WORKFLOW_OWNER,
  OPERATION_WORKFLOW_PROGRESS_DECISION_KERNEL,
  OPERATION_WORKFLOW_REASON_CODE_VALUES,
} from '../../src/rebalancer/operation-workflow-owner-constants.js';

import {
  registerPriorityRecoverySnapshotCore01Tests,
} from './priority-recovery-snapshot-core-01-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore02Tests,
} from './priority-recovery-snapshot-core-02-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore03Tests,
} from './priority-recovery-snapshot-core-03-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore04Tests,
} from './priority-recovery-snapshot-core-04-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore05Tests,
} from './priority-recovery-snapshot-core-05-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore06Tests,
} from './priority-recovery-snapshot-core-06-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore07Tests,
} from './priority-recovery-snapshot-core-07-test-cases.js';
import {
  registerPriorityRecoverySnapshotCore08Tests,
} from './priority-recovery-snapshot-core-08-test-cases.js';
import {
  registerPriorityRecoverySnapshotSupplementalTests,
} from './priority-recovery-snapshot-supplemental-test-cases.js';
const PUBLICATION_PRIORITY_PARTITION_ID = 'control_plane_publications-p1';
const REPLICA_OPERATION_PRIORITY_PARTITION_ID = 'replica_operations-p1';
const SQL_TRANSACTION_PRIORITY_PARTITION_ID = 'sql_transactions-p1';
const PRIORITY_RECOVERY_REASON_OPERATIONAL_TARGET_VISIBLE_ON_ELIGIBLE_NODE =
  'operational_target_visible_on_eligible_node';
const PRIORITY_RECOVERY_SEMANTIC_STATE_SPREAD_SATISFIED_IN_FLIGHT =
  'spread_satisfied_in_flight';
const PRIORITY_RECOVERY_SEMANTIC_STATE_RECOVERING_IN_FLIGHT =
  'recovering_in_flight';
const PRIORITY_RECOVERY_SEMANTIC_STATE_CONVERGED = 'converged';
const PRIORITY_RECOVERY_SEMANTIC_STATE_OPERATION_STALLED =
  'operation_stalled';
const PRIORITY_RECOVERY_SEMANTIC_STATE_LEARNER_PROMOTION_BLOCKED =
  'learner_promotion_blocked';
const PRIORITY_RECOVERY_SEMANTIC_STATE_COORDINATION_MISMATCH =
  'coordination_mismatch';
const PRIORITY_RECOVERY_SEMANTIC_STATE_BLOCKED_UNCLASSIFIED =
  'blocked_unclassified';
const PRIORITY_RECOVERY_VISIBILITY_STATE_CACHE_VISIBLE = 'cache_visible';
const PRIORITY_RECOVERY_WORKFLOW_STATE_REMOVE_PHASE = 'remove_phase';
const PRIORITY_RECOVERY_CONVERGENCE_STATE_CONVERGED = 'converged';
const PRIORITY_RECOVERY_CONVERGENCE_STATE_CONVERGING = 'converging';
const PRIORITY_RECOVERY_PROTOCOL_STATE_PRIORITY_SPREAD_PENDING =
  'priority_spread_pending';
const PRIORITY_RECOVERY_REASON_PRIORITY_PARTITIONS_NOT_SPREAD =
  'priority_partitions_not_spread';
const PRIORITY_RECOVERY_WORKFLOW_STATE_IN_FLIGHT = 'in_flight';
const PRIORITY_RECOVERY_NODE_ID_A = 'node-a';
const PRIORITY_RECOVERY_NODE_ID_B = 'node-b';
const PRIORITY_RECOVERY_NODE_ID_C = 'node-c';
const PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_PARTITION_ID =
  'sql_transaction_participants-p1';
const PRIORITY_RECOVERY_PUBLICATION_STATUS_PUBLISHED = 'PUBLISHED';
const PRIORITY_RECOVERY_ENTITY_TYPE_PARTITION = 'partition';
const PRIORITY_RECOVERY_REASON_PLANNER_READY = 'planner_ready';
const PRIORITY_RECOVERY_SAMPLE_PUBLICATION_EPOCH = 12;
const PRIORITY_RECOVERY_SAMPLE_CAPTURED_AT_MS = 5000;
const PRIORITY_RECOVERY_REQUIRED_DISTINCT_NODE_COUNT = 3;
const PRIORITY_RECOVERY_READY_ELIGIBLE_NODE_COUNT = 6;
const PRIORITY_RECOVERY_TOTAL_PRIORITY_PARTITION_COUNT = 5;
const PRIORITY_RECOVERY_OPERATION_CREATED_AT_MS = 1000;
const PRIORITY_RECOVERY_OPERATION_ID_SYNCING = 'op-replace-syncing';
const PRIORITY_RECOVERY_OPERATION_ID_TERMINAL_REPLACE = 'op-terminal-replace';
const PRIORITY_RECOVERY_REPLICA_ID_SYNCING =
  'sql_transaction_participants-p1-r4';
const PRIORITY_RECOVERY_REASON_CLUSTER_MEMBER_UNHEALTHY =
  'cluster_member_unhealthy';
const PRIORITY_RECOVERY_ADMISSION_STATE_BLOCKED = 'blocked';
const PRIORITY_RECOVERY_ADMISSION_REASON_CLUSTER_INTEGRITY =
  'cluster_incarnation_identity_mismatch';
const PRIORITY_RECOVERY_BLOCKED_FENCE = Object.freeze({
  state: 'identity_mismatch',
  allowed: false,
  reasonCodes: Object.freeze([
    PRIORITY_RECOVERY_ADMISSION_REASON_CLUSTER_INTEGRITY,
  ]),
});
const PRIORITY_RECOVERY_REASON_CONTROL_PLANE_WRITE_UNHEALTHY =
  'control_plane_write_unhealthy';
const PRIORITY_RECOVERY_STATUS_ACTIVE = 'active';
const PRIORITY_RECOVERY_STATUS_COMPLETED = 'completed';
const PRIORITY_RECOVERY_STATUS_CREATING = 'creating';
const PRIORITY_RECOVERY_STATUS_FAILED = 'failed';
const PRIORITY_RECOVERY_STATUS_PENDING = 'pending';
const PRIORITY_RECOVERY_STATUS_REMOVED = 'removed';
const PRIORITY_RECOVERY_STATUS_SYNCING = 'syncing';
const PRIORITY_RECOVERY_RAFT_ROLE_LEARNER = 'learner';
const PRIORITY_RECOVERY_RAFT_ROLE_FOLLOWER = 'follower';
const PRIORITY_RECOVERY_RAFT_ROLE_VOTER = 'voter';
const PRIORITY_RECOVERY_OPERATION_TYPE_ADD = 'ADD';
const PRIORITY_RECOVERY_OPERATION_TYPE_REPLACE = 'REPLACE';
const PRIORITY_RECOVERY_WORKFLOW_STEP_PENDING = 'PENDING';
const PRIORITY_RECOVERY_WORKFLOW_STEP_SENDING = 'SENDING';
const PRIORITY_RECOVERY_WORKFLOW_STEP_CREATING = 'CREATING';
const PRIORITY_RECOVERY_WORKFLOW_STEP_FAILED = 'FAILED';
const PRIORITY_RECOVERY_WORKFLOW_STEP_SYNCING = 'SYNCING';
const PRIORITY_RECOVERY_WORKFLOW_STEP_ACTIVE = 'ACTIVE';
const PRIORITY_RECOVERY_WORKFLOW_STEP_REMOVED = 'REMOVED';
const PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_PENDING = 'pending';
const PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_BLOCKED = 'blocked';
const PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_DEFERRED = 'deferred';
const PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_READY = 'ready';
const PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_WAIT = 'wait';
const PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_RETRY = 'retry';
const PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_STOP = 'stop';
const PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_PROCEED = 'proceed';
const PRIORITY_RECOVERY_PROGRESS_OWNER_WORKFLOW = 'operation_workflow_owner';
const PRIORITY_RECOVERY_PROGRESS_OWNER_REBALANCER = 'rebalancer_leader';
const PRIORITY_RECOVERY_PROGRESS_OWNER_VISIBILITY =
  'authoritative_visibility_owner';
const PRIORITY_RECOVERY_PROGRESS_OWNER_NONE = 'none';
const PRIORITY_RECOVERY_PROGRESS_ACTION_NONE = 'none';
const PRIORITY_RECOVERY_PROGRESS_ACTION_WAIT_FOR_PROGRESS =
  'wait_for_operation_progress';
const PRIORITY_RECOVERY_PROGRESS_ACTION_ADVANCE_EXISTING_OPERATION =
  'advance_existing_operation';
const PRIORITY_RECOVERY_PROGRESS_ACTION_RECONCILE_STALE_OPERATION =
  'reconcile_stale_operation_progress';
const PRIORITY_RECOVERY_PROGRESS_ACTION_OBSERVE_VISIBILITY =
  'observe_authoritative_visibility';
const PRIORITY_RECOVERY_PROGRESS_ACTION_CREATE_OPERATION =
  'create_recovery_operation';
const PRIORITY_RECOVERY_PROGRESS_BOUNDARY_WORKFLOW = 'workflow_progress';
const PRIORITY_RECOVERY_PROGRESS_BOUNDARY_WORKFLOW_TIMEOUT =
  'workflow_timeout';
const PRIORITY_RECOVERY_PROGRESS_BOUNDARY_VISIBILITY =
  'authoritative_visibility';
const PRIORITY_RECOVERY_PROGRESS_BOUNDARY_SCHEDULING =
  'operation_scheduling';
const PRIORITY_RECOVERY_PROGRESS_BOUNDARY_NONE = 'none';
const PRIORITY_RECOVERY_PROGRESS_WAIT_EVENT_DRIVEN = 'event_driven';
const PRIORITY_RECOVERY_PROGRESS_WAIT_RETRY_SCHEDULED = 'retry_scheduled';
const PRIORITY_RECOVERY_PROGRESS_WAIT_TIMEOUT_RECONCILE_DUE =
  'timeout_reconcile_due';
const PRIORITY_RECOVERY_PROGRESS_WAIT_DEFERRED_VISIBILITY =
  'deferred_visibility';
const PRIORITY_RECOVERY_PROGRESS_WAIT_STALLED = 'stalled';
const PRIORITY_RECOVERY_PROGRESS_WAIT_NONE = 'none';
const PRIORITY_RECOVERY_PROGRESS_PHASE_DISPATCH_PENDING =
  'dispatch_pending';
const PRIORITY_RECOVERY_PROGRESS_PHASE_TARGET_CREATION = 'target_creation';
const PRIORITY_RECOVERY_PROGRESS_PHASE_SOURCE_REMOVAL = 'source_removal';
const PRIORITY_RECOVERY_PENDING_TIMEOUT_MS = 30000;
const PRIORITY_RECOVERY_PENDING_SHORT_TIMEOUT_MS = 1000;
const PRIORITY_RECOVERY_CREATING_TIMEOUT_MS = 60000;
const PRIORITY_RECOVERY_ACTIVE_SOURCE_REMOVAL_AGE_MS = 134113;
const PRIORITY_RECOVERY_ACTUATION_STATE_ACTION_REQUIRED =
  'action_required';
const PRIORITY_RECOVERY_ACTUATION_STATE_NO_ACTION_NEEDED =
  'no_action_needed';
const PRIORITY_RECOVERY_ACTUATION_STATE_PERSISTED_NOT_DISPATCHED =
  'persisted_not_dispatched';
const PRIORITY_RECOVERY_ACTUATION_STATE_DISPATCHED_WAITING_PROGRESS =
  'dispatched_waiting_progress';
const PRIORITY_RECOVERY_ACTUATION_STATE_TRANSITION_DEFERRED =
  'transition_deferred';
const PRIORITY_RECOVERY_ACTUATION_STATE_TERMINAL_COMPLETED =
  'terminal_completed';
const PRIORITY_RECOVERY_PRESSURE_STATE_NONE = 'none';
const PRIORITY_RECOVERY_PRESSURE_STATE_WRITE_BACKLOG = 'write_backlog';
const PRIORITY_RECOVERY_PRESSURE_STATE_BACKPRESSURED = 'backpressured';
const PRIORITY_RECOVERY_PROGRESS_EVIDENCE_OPERATION_CONTEXT =
  'operation_context';
const PRIORITY_RECOVERY_PROGRESS_EVIDENCE_WORKFLOW_STATE = 'workflow_state';
const PRIORITY_RECOVERY_PROGRESS_EVIDENCE_LAST_PROGRESS =
  'last_progress_timestamp';
const PRIORITY_RECOVERY_OPERATION_ID_SYNCING_FOLLOWER_TARGET =
  'op-replace-syncing-follower-target';
const PRIORITY_RECOVERY_OPERATION_ID_SERIAL_LANE_ADD =
  'op-ordinary-priority-serial-lane-add';
const PRIORITY_RECOVERY_PUBLICATION_REPLACEMENT_REPLICA_ID =
  'control_plane_publications-p1-r4';
const PRIORITY_RECOVERY_PUBLICATION_REPLACEMENT_ADDRESS =
  'node-b/partition/control_plane_publications-p1-r4';
const PRIORITY_RECOVERY_BLOCKER_REASON_OPERATION_NO_TRANSITIONS =
  'operation_created_but_no_step_transitions';
const PRIORITY_RECOVERY_BLOCKER_REASON_SERIAL_OPERATION_WAIT =
  'priority_operation_serial_wait';
const PRIORITY_RECOVERY_BLOCKER_REASON_ELIGIBLE_NO_OPERATION =
  'eligible_but_no_operation_created';
const PRIORITY_RECOVERY_BLOCKER_REASON_RECOVERY_ELIGIBLE_EXCLUDED =
  'publication_recovery_eligible_but_coordinator_excludes_node';
const PRIORITY_RECOVERY_SEMANTIC_STATE_NEEDS_OPERATION =
  'needs_operation';
const PRIORITY_RECOVERY_OPERATION_ID_OBJECT_ONLY =
  'op-visible-from-operation-object';
const PRIORITY_RECOVERY_OPERATION_ID_PENDING_PLANNER_READY =
  'op-pending-planner-ready';
const PRIORITY_RECOVERY_OPERATION_ID_COMPLETED_REPLACE_VISIBLE =
  'op-completed-replace-visible';
const PRIORITY_RECOVERY_OPERATION_ID_PENDING_REPLACE_STALE =
  'op-pending-replace-stale';
const PRIORITY_RECOVERY_OPERATION_ID_SUPERSEDED_SYNCING =
  'op-superseded-syncing';
const PRIORITY_RECOVERY_OPERATION_ID_NEWER_FAILED_REPLACE =
  'op-newer-failed-replace';
const PRIORITY_RECOVERY_OPERATION_ID_FAILED_REPLACE_ACTIVE_TARGET =
  'op-failed-replace-active-target';
const PRIORITY_RECOVERY_OPERATION_ID_ELIGIBLE_REMOVE_PHASE =
  'op-eligible-remove-phase';
const PRIORITY_RECOVERY_OPERATION_ID_EXCLUDED_TARGET_CREATING =
  'op-excluded-target-creating';
const PRIORITY_RECOVERY_OPERATION_ID_PENDING_OWNER_WAIT =
  'op-pending-dispatch-owner-wait';
const PRIORITY_RECOVERY_OPERATION_ID_TARGET_SERVICE_PROGRESS =
  'op-target-service-progress';
const PRIORITY_RECOVERY_REPLICA_ID_TARGET_SERVICE_PROGRESS =
  'control_plane_publications-p1-r5';
const PRIORITY_RECOVERY_STALE_OPERATION_PROGRESS_AT_MS = 1000;
const PRIORITY_RECOVERY_TARGET_SERVICE_PROGRESS_AT_MS = 34000;
const PRIORITY_RECOVERY_TARGET_SERVICE_CAPTURED_AT_MS = 35000;
const PRIORITY_RECOVERY_HIGHER_EPOCH_VALUE = 5;
const PRIORITY_RECOVERY_LOWER_EPOCH_VALUE = 2;
const PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_CAPTURED_AT_MS = 3600;
const PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_UPDATED_AT_MS = 3400;
const PRIORITY_RECOVERY_LOWER_EPOCH_SYNTHETIC_CAPTURED_AT_MS = 4000;
const PRIORITY_RECOVERY_OBSERVATION_STATE_NONE = 'none';
const PRIORITY_RECOVERY_CONVERGENCE_STATE_SPREAD_GAP = 'spread_gap';
const PRIORITY_RECOVERY_TARGET_VISIBILITY_ACTIVE_OPERATIONAL =
  'active_operational';
const PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_OPERATION_ID =
  'op-higher-epoch-progress';
const PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_CORRELATION_KEY =
  `${REPLICA_OPERATION_PRIORITY_PARTITION_ID}|` +
  `${PRIORITY_RECOVERY_HIGHER_EPOCH_VALUE}|` +
  `${PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_OPERATION_ID}`;
const PRIORITY_RECOVERY_FAILED_REPLACE_ACTIVE_TARGET_TEST_NAME =
  'priority recovery failed REPLACE with active target satisfies spread instead of missing operation';
const PRIORITY_RECOVERY_SERIAL_WAIT_WITNESS_TEST_NAME =
  'priority recovery serial-wait witnesses retain blocking operation evidence';
const PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_TEST_NAME =
  'priority recovery serial-wait ignores spread-satisfying replace targets';
const PRIORITY_RECOVERY_ACTIVE_TARGET_NOT_MISSING_OPERATION_MESSAGE =
  'an active operational replacement target should not be reported as missing operation work';
const PRIORITY_RECOVERY_ACTIVE_TARGET_SPREAD_WITNESS_MESSAGE =
  'the failed replacement should still witness spread when its target is active operational on an eligible node';
const PRIORITY_RECOVERY_ACTIVE_TARGET_SEMANTIC_MESSAGE =
  'the partition should leave needs_operation once the active target satisfies recovery';
const PRIORITY_RECOVERY_ACTIVE_TARGET_COMPLETION_MESSAGE =
  'completion should use the spread-satisfied recovery state';
const PRIORITY_RECOVERY_ACTIVE_TARGET_PROGRESS_MESSAGE =
  'the progress contract should not schedule a duplicate recovery operation';
const PRIORITY_RECOVERY_SERIAL_WAIT_OPERATION_IDS_MESSAGE =
  'serial-wait witnesses should keep current-partition operation ids separate';
const PRIORITY_RECOVERY_SERIAL_WAIT_BLOCKING_OPERATION_MESSAGE =
  'serial-wait witnesses should expose the operation that owns the serial lane';
const PRIORITY_RECOVERY_SERIAL_WAIT_BLOCKING_PARTITION_MESSAGE =
  'serial-wait witnesses should expose the partition that owns the serial lane';
const PRIORITY_RECOVERY_SERIAL_WAIT_WITNESS_ID_MESSAGE =
  'serial-wait operation ids should remain diagnostic witness ids';
const PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_MESSAGE =
  'spread-satisfying ordinary-lane replacements should not retain the serial wait blocker';
const PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_PROGRESS_MESSAGE =
  'released serial-wait partitions should return to scheduling ownership';
const PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_TEST_NAME =
  'tracked priority recovery decision snapshots release stale serial-wait blockers when fresher terminal evidence exists';
const PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_MESSAGE =
  'fresher terminal spread satisfaction should clear stale serial-wait bookkeeping';
const PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_PROGRESS_MESSAGE =
  'released serial wait should return the blocked partition to scheduling ownership';
const PRIORITY_RECOVERY_SQL_TRANSACTIONS_REPLICA_ID =
  'sql_transactions-p1-r5';
const PRIORITY_RECOVERY_SQL_TRANSACTIONS_REPLACEMENT_REPLICA_ID =
  'sql_transactions-p1-r6';
const PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_REPLACEMENT_REPLICA_ID =
  'sql_transaction_participants-p1-r7';
const PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_STALE_REPLICA_ID =
  'sql_transaction_participants-p1-r8';
const PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_FAILED_REPLICA_ID =
  'sql_transaction_participants-p1-r9';
const PRIORITY_RECOVERY_SQL_WRITE_OPERATIONS_PARTITION_ID =
  'sql_write_operations-p1';
const PRIORITY_RECOVERY_OPERATION_ID_EXCLUDED_COMPLETED_REPLACE =
  'op-excluded-completed-replace';
const PRIORITY_RECOVERY_OPERATION_ID_CREATING_REPLACE_STALE =
  'op-creating-replace-stale';
const PRIORITY_RECOVERY_OPERATION_ID_RELEASED_SERIAL_WAIT =
  'op-released-serial-wait';
const PRIORITY_RECOVERY_SQL_WRITE_COMPLETED_REPLICA_ID =
  'sql_write_operations-p1-r4';
const PRIORITY_RECOVERY_SQL_WRITE_CREATING_REPLICA_ID =
  'sql_write_operations-p1-r5';
const PRIORITY_RECOVERY_OPERATION_UPDATED_AT_MS = 2000;
const PRIORITY_RECOVERY_OPERATION_COMPLETED_AT_MS = 2500;
const PRIORITY_RECOVERY_STALE_SERIAL_WAIT_CAPTURED_AT_MS = 4500;
const PRIORITY_RECOVERY_RELEASED_SERIAL_WAIT_CAPTURED_AT_MS = 5000;
const PRIORITY_RECOVERY_RELEASED_SERIAL_WAIT_PROGRESS_AT_MS = 4900;
const PRIORITY_RECOVERY_PENDING_CAPTURED_AT_MS = 2500;
const PRIORITY_RECOVERY_PENDING_OPERATION_UPDATED_AT_MS = 1000;
const PRIORITY_RECOVERY_ARTIFACT_PUBLICATION_EPOCH = 3;
const PRIORITY_RECOVERY_ARTIFACT_PENDING_ACK_NODE_ID =
  '11601fe0-72d6-5853-8590-ec2881853e72';
const PRIORITY_RECOVERY_ARTIFACT_SOURCE_NODE_ID =
  '7493b0ab-a054-5fad-a91b-5e331db29304';
const PRIORITY_RECOVERY_ARTIFACT_TARGET_NODE_ID =
  'ebc4aa0b-06c6-506d-93ea-1dd2deca3f58';
const PRIORITY_RECOVERY_ARTIFACT_PENDING_OPERATION_ID =
  '7a24201b-6f3c-4298-a32c-4efe04157ff9';
const PRIORITY_RECOVERY_ARTIFACT_SQL_TRANSACTIONS_REPLICA_ID =
  'sql_transactions-p1-r4';
const PRIORITY_RECOVERY_ARTIFACT_OPERATION_CREATED_AT_MS = 1778083009776;
const PRIORITY_RECOVERY_ARTIFACT_OPERATION_CAPTURED_AT_MS = 1778083032564;
const PRIORITY_RECOVERY_ARTIFACT_SYNTHETIC_CAPTURED_AT_MS = 1778083033777;
const PRIORITY_RECOVERY_ARTIFACT_OPERATION_STEP_AGE_MS =
  PRIORITY_RECOVERY_ARTIFACT_SYNTHETIC_CAPTURED_AT_MS -
  PRIORITY_RECOVERY_ARTIFACT_OPERATION_CREATED_AT_MS;
const PRIORITY_RECOVERY_ARTIFACT_REQUIRED_DISTINCT_NODE_COUNT = 2;
const PRIORITY_RECOVERY_ARTIFACT_READY_DISTINCT_NODE_COUNT = 1;
const PRIORITY_RECOVERY_SUPERSEDED_OPERATION_UPDATED_AT_MS = 3000;
const PRIORITY_RECOVERY_NEWER_OPERATION_CREATED_AT_MS = 4000;
const PRIORITY_RECOVERY_NEWER_OPERATION_COMPLETED_AT_MS = 4500;
const PRIORITY_RECOVERY_STALE_READY_DISTINCT_NODE_COUNT = 2;
const PRIORITY_RECOVERY_SINGLE_SPREAD_GAP = 1;
const PRIORITY_RECOVERY_EMPTY_COUNT = 0;
const PRIORITY_RECOVERY_SINGLE_OPERATION_COUNT = 1;
const PRIORITY_RECOVERY_FIRST_PARTITION_WITNESS_INDEX = 0;
const PRIORITY_RECOVERY_EMPTY_OPERATION_IDS = Object.freeze([]);
const PRIORITY_RECOVERY_ABSENT_OPERATION = null;
const PRIORITY_RECOVERY_SINGLE_ADD_BUDGET_LIMIT = 1;
const PRIORITY_RECOVERY_SINGLE_EMERGENCY_OVERFLOW_SLOT_COUNT = 1;
const PRIORITY_RECOVERY_DUAL_EMERGENCY_OVERFLOW_SLOT_COUNT = 2;
const PRIORITY_RECOVERY_SINGLE_EMERGENCY_BUDGET_LIMIT = 2;
const PRIORITY_RECOVERY_DUAL_EMERGENCY_BUDGET_LIMIT = 3;
const PRIORITY_RECOVERY_SINGLE_PRIORITY_IN_FLIGHT_COUNT = 1;
const PRIORITY_RECOVERY_DUAL_PRIORITY_IN_FLIGHT_COUNT = 2;
const PRIORITY_RECOVERY_TERMINAL_REPLACE_OPERATION_CONTEXT = Object.freeze({
  partitionId: PUBLICATION_PRIORITY_PARTITION_ID,
  operationId: PRIORITY_RECOVERY_OPERATION_ID_TERMINAL_REPLACE,
  type: 'REPLACE',
  status: PRIORITY_RECOVERY_STATUS_COMPLETED,
  workflowStep: PRIORITY_RECOVERY_WORKFLOW_STEP_REMOVED,
  targetNodeId: PRIORITY_RECOVERY_NODE_ID_B,
  updatedAtMs: 1400,
  completedAtMs: 1500,
  timelineLength: 3,
  timelineStepCount: 3,
  latestTimelineStep: PRIORITY_RECOVERY_WORKFLOW_STEP_REMOVED,
  latestTimelineStatus: PRIORITY_RECOVERY_STATUS_COMPLETED,
  latestTimelineInFlight: false,
});

const priorityRecoverySnapshotTestContext = {
  buildPriorityRecoveryActuationDecisionInput,
  buildPriorityRecoveryAdmissionPlan,
  buildPriorityRecoveryClosureWitness,
  buildPriorityRecoveryDecisionSnapshot,
  buildPriorityRecoveryDecisionSnapshots,
  buildPriorityRecoveryObservationSnapshot,
  buildPriorityRecoveryPublicationContext,
  buildTrackedPriorityRecoveryDecisionSnapshots,
  CONTROL_PLANE_READINESS_DIMENSION,
  isPriorityRecoveryEmergencyPartition,
  normalizePriorityRecoveryDispatchPendingDecisionSnapshot,
  OPERATION_WORKFLOW_EFFECT_COMMAND_VALUES,
  OPERATION_WORKFLOW_OUTCOME_VALUES,
  OPERATION_WORKFLOW_OWNER,
  OPERATION_WORKFLOW_PROGRESS_DECISION_KERNEL,
  OPERATION_WORKFLOW_REASON_CODE_VALUES,
  PRIORITY_RECOVERY_ABSENT_OPERATION,
  PRIORITY_RECOVERY_ACTIVE_SOURCE_REMOVAL_AGE_MS,
  PRIORITY_RECOVERY_ACTIVE_TARGET_COMPLETION_MESSAGE,
  PRIORITY_RECOVERY_ACTIVE_TARGET_NOT_MISSING_OPERATION_MESSAGE,
  PRIORITY_RECOVERY_ACTIVE_TARGET_PROGRESS_MESSAGE,
  PRIORITY_RECOVERY_ACTIVE_TARGET_SEMANTIC_MESSAGE,
  PRIORITY_RECOVERY_ACTIVE_TARGET_SPREAD_WITNESS_MESSAGE,
  PRIORITY_RECOVERY_ACTUATION_STATE_ACTION_REQUIRED,
  PRIORITY_RECOVERY_ACTUATION_STATE_DISPATCHED_WAITING_PROGRESS,
  PRIORITY_RECOVERY_ACTUATION_STATE_NO_ACTION_NEEDED,
  PRIORITY_RECOVERY_ACTUATION_STATE_PERSISTED_NOT_DISPATCHED,
  PRIORITY_RECOVERY_ACTUATION_STATE_TERMINAL_COMPLETED,
  PRIORITY_RECOVERY_ACTUATION_STATE_TRANSITION_DEFERRED,
  PRIORITY_RECOVERY_ADMISSION_DECISION_REASON,
  PRIORITY_RECOVERY_ADMISSION_PARTITION_CLASS,
  PRIORITY_RECOVERY_ADMISSION_REASON_CLUSTER_INTEGRITY,
  PRIORITY_RECOVERY_ADMISSION_SOURCE,
  PRIORITY_RECOVERY_ADMISSION_STATE_BLOCKED,
  PRIORITY_RECOVERY_ARTIFACT_OPERATION_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_ARTIFACT_OPERATION_CREATED_AT_MS,
  PRIORITY_RECOVERY_ARTIFACT_OPERATION_STEP_AGE_MS,
  PRIORITY_RECOVERY_ARTIFACT_PENDING_ACK_NODE_ID,
  PRIORITY_RECOVERY_ARTIFACT_PENDING_OPERATION_ID,
  PRIORITY_RECOVERY_ARTIFACT_PUBLICATION_EPOCH,
  PRIORITY_RECOVERY_ARTIFACT_READY_DISTINCT_NODE_COUNT,
  PRIORITY_RECOVERY_ARTIFACT_REQUIRED_DISTINCT_NODE_COUNT,
  PRIORITY_RECOVERY_ARTIFACT_SOURCE_NODE_ID,
  PRIORITY_RECOVERY_ARTIFACT_SQL_TRANSACTIONS_REPLICA_ID,
  PRIORITY_RECOVERY_ARTIFACT_SYNTHETIC_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_ARTIFACT_TARGET_NODE_ID,
  PRIORITY_RECOVERY_BLOCKED_FENCE,
  PRIORITY_RECOVERY_BLOCKER_REASON_ELIGIBLE_NO_OPERATION,
  PRIORITY_RECOVERY_BLOCKER_REASON_OPERATION_NO_TRANSITIONS,
  PRIORITY_RECOVERY_BLOCKER_REASON_RECOVERY_ELIGIBLE_EXCLUDED,
  PRIORITY_RECOVERY_BLOCKER_REASON_SERIAL_OPERATION_WAIT,
  PRIORITY_RECOVERY_CLOSURE_RECORD_ID,
  PRIORITY_RECOVERY_CLOSURE_WITNESS_CLASS,
  PRIORITY_RECOVERY_CLOSURE_WITNESS_STATE,
  PRIORITY_RECOVERY_COMPLETION_STATE,
  PRIORITY_RECOVERY_CONVERGENCE_STATE_CONVERGED,
  PRIORITY_RECOVERY_CONVERGENCE_STATE_CONVERGING,
  PRIORITY_RECOVERY_CONVERGENCE_STATE_SPREAD_GAP,
  PRIORITY_RECOVERY_CREATING_TIMEOUT_MS,
  PRIORITY_RECOVERY_DECISION_SNAPSHOT_EXPECTED,
  PRIORITY_RECOVERY_DUAL_EMERGENCY_BUDGET_LIMIT,
  PRIORITY_RECOVERY_DUAL_EMERGENCY_OVERFLOW_SLOT_COUNT,
  PRIORITY_RECOVERY_DUAL_PRIORITY_IN_FLIGHT_COUNT,
  PRIORITY_RECOVERY_EMPTY_COUNT,
  PRIORITY_RECOVERY_EMPTY_OPERATION_IDS,
  PRIORITY_RECOVERY_ENTITY_TYPE_PARTITION,
  PRIORITY_RECOVERY_FAILED_REPLACE_ACTIVE_TARGET_TEST_NAME,
  PRIORITY_RECOVERY_FIRST_PARTITION_WITNESS_INDEX,
  PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_CORRELATION_KEY,
  PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_OPERATION_ID,
  PRIORITY_RECOVERY_HIGHER_EPOCH_PROGRESS_UPDATED_AT_MS,
  PRIORITY_RECOVERY_HIGHER_EPOCH_VALUE,
  PRIORITY_RECOVERY_LOWER_EPOCH_SYNTHETIC_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_LOWER_EPOCH_VALUE,
  PRIORITY_RECOVERY_NEWER_OPERATION_COMPLETED_AT_MS,
  PRIORITY_RECOVERY_NEWER_OPERATION_CREATED_AT_MS,
  PRIORITY_RECOVERY_NODE_ID_A,
  PRIORITY_RECOVERY_NODE_ID_B,
  PRIORITY_RECOVERY_NODE_ID_C,
  PRIORITY_RECOVERY_OBSERVATION_STATE_NONE,
  PRIORITY_RECOVERY_OPERATION_COMPLETED_AT_MS,
  PRIORITY_RECOVERY_OPERATION_CREATED_AT_MS,
  PRIORITY_RECOVERY_OPERATION_ID_COMPLETED_REPLACE_VISIBLE,
  PRIORITY_RECOVERY_OPERATION_ID_CREATING_REPLACE_STALE,
  PRIORITY_RECOVERY_OPERATION_ID_ELIGIBLE_REMOVE_PHASE,
  PRIORITY_RECOVERY_OPERATION_ID_EXCLUDED_COMPLETED_REPLACE,
  PRIORITY_RECOVERY_OPERATION_ID_EXCLUDED_TARGET_CREATING,
  PRIORITY_RECOVERY_OPERATION_ID_FAILED_REPLACE_ACTIVE_TARGET,
  PRIORITY_RECOVERY_OPERATION_ID_NEWER_FAILED_REPLACE,
  PRIORITY_RECOVERY_OPERATION_ID_OBJECT_ONLY,
  PRIORITY_RECOVERY_OPERATION_ID_PENDING_OWNER_WAIT,
  PRIORITY_RECOVERY_OPERATION_ID_PENDING_PLANNER_READY,
  PRIORITY_RECOVERY_OPERATION_ID_PENDING_REPLACE_STALE,
  PRIORITY_RECOVERY_OPERATION_ID_RELEASED_SERIAL_WAIT,
  PRIORITY_RECOVERY_OPERATION_ID_SERIAL_LANE_ADD,
  PRIORITY_RECOVERY_OPERATION_ID_SUPERSEDED_SYNCING,
  PRIORITY_RECOVERY_OPERATION_ID_SYNCING,
  PRIORITY_RECOVERY_OPERATION_ID_SYNCING_FOLLOWER_TARGET,
  PRIORITY_RECOVERY_OPERATION_ID_TARGET_SERVICE_PROGRESS,
  PRIORITY_RECOVERY_OPERATION_ID_TERMINAL_REPLACE,
  PRIORITY_RECOVERY_OPERATION_TYPE_ADD,
  PRIORITY_RECOVERY_OPERATION_TYPE_REPLACE,
  PRIORITY_RECOVERY_OPERATION_UPDATED_AT_MS,
  PRIORITY_RECOVERY_PENDING_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_PENDING_OPERATION_UPDATED_AT_MS,
  PRIORITY_RECOVERY_PENDING_SHORT_TIMEOUT_MS,
  PRIORITY_RECOVERY_PENDING_TIMEOUT_MS,
  PRIORITY_RECOVERY_PRESSURE_STATE_BACKPRESSURED,
  PRIORITY_RECOVERY_PRESSURE_STATE_NONE,
  PRIORITY_RECOVERY_PRESSURE_STATE_WRITE_BACKLOG,
  PRIORITY_RECOVERY_PROGRESS_ACTION_ADVANCE_EXISTING_OPERATION,
  PRIORITY_RECOVERY_PROGRESS_ACTION_CREATE_OPERATION,
  PRIORITY_RECOVERY_PROGRESS_ACTION_NONE,
  PRIORITY_RECOVERY_PROGRESS_ACTION_OBSERVE_VISIBILITY,
  PRIORITY_RECOVERY_PROGRESS_ACTION_RECONCILE_STALE_OPERATION,
  PRIORITY_RECOVERY_PROGRESS_ACTION_WAIT_FOR_PROGRESS,
  PRIORITY_RECOVERY_PROGRESS_BOUNDARY_NONE,
  PRIORITY_RECOVERY_PROGRESS_BOUNDARY_SCHEDULING,
  PRIORITY_RECOVERY_PROGRESS_BOUNDARY_VISIBILITY,
  PRIORITY_RECOVERY_PROGRESS_BOUNDARY_WORKFLOW,
  PRIORITY_RECOVERY_PROGRESS_BOUNDARY_WORKFLOW_TIMEOUT,
  PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_BLOCKED,
  PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_DEFERRED,
  PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_PENDING,
  PRIORITY_RECOVERY_PROGRESS_CONTRACT_STATE_READY,
  PRIORITY_RECOVERY_PROGRESS_EVIDENCE_LAST_PROGRESS,
  PRIORITY_RECOVERY_PROGRESS_EVIDENCE_OPERATION_CONTEXT,
  PRIORITY_RECOVERY_PROGRESS_EVIDENCE_WORKFLOW_STATE,
  PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_PROCEED,
  PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_RETRY,
  PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_STOP,
  PRIORITY_RECOVERY_PROGRESS_NEXT_ACTION_WAIT,
  PRIORITY_RECOVERY_PROGRESS_OWNER_NONE,
  PRIORITY_RECOVERY_PROGRESS_OWNER_REBALANCER,
  PRIORITY_RECOVERY_PROGRESS_OWNER_VISIBILITY,
  PRIORITY_RECOVERY_PROGRESS_OWNER_WORKFLOW,
  PRIORITY_RECOVERY_PROGRESS_PHASE_DISPATCH_PENDING,
  PRIORITY_RECOVERY_PROGRESS_PHASE_SOURCE_REMOVAL,
  PRIORITY_RECOVERY_PROGRESS_PHASE_TARGET_CREATION,
  PRIORITY_RECOVERY_PROGRESS_WAIT_DEFERRED_VISIBILITY,
  PRIORITY_RECOVERY_PROGRESS_WAIT_EVENT_DRIVEN,
  PRIORITY_RECOVERY_PROGRESS_WAIT_NONE,
  PRIORITY_RECOVERY_PROGRESS_WAIT_RETRY_SCHEDULED,
  PRIORITY_RECOVERY_PROGRESS_WAIT_STALLED,
  PRIORITY_RECOVERY_PROGRESS_WAIT_TIMEOUT_RECONCILE_DUE,
  PRIORITY_RECOVERY_PROTOCOL_STATE_PRIORITY_SPREAD_PENDING,
  PRIORITY_RECOVERY_PUBLICATION_REPLACEMENT_ADDRESS,
  PRIORITY_RECOVERY_PUBLICATION_REPLACEMENT_REPLICA_ID,
  PRIORITY_RECOVERY_PUBLICATION_STATUS_PUBLISHED,
  PRIORITY_RECOVERY_RAFT_ROLE_FOLLOWER,
  PRIORITY_RECOVERY_RAFT_ROLE_LEARNER,
  PRIORITY_RECOVERY_RAFT_ROLE_VOTER,
  PRIORITY_RECOVERY_READY_ELIGIBLE_NODE_COUNT,
  PRIORITY_RECOVERY_REASON_CLUSTER_MEMBER_UNHEALTHY,
  PRIORITY_RECOVERY_REASON_CONTROL_PLANE_WRITE_UNHEALTHY,
  PRIORITY_RECOVERY_REASON_OPERATIONAL_TARGET_VISIBLE_ON_ELIGIBLE_NODE,
  PRIORITY_RECOVERY_REASON_PLANNER_READY,
  PRIORITY_RECOVERY_REASON_PRIORITY_PARTITIONS_NOT_SPREAD,
  PRIORITY_RECOVERY_RELEASED_SERIAL_WAIT_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_RELEASED_SERIAL_WAIT_PROGRESS_AT_MS,
  PRIORITY_RECOVERY_REPLICA_ID_SYNCING,
  PRIORITY_RECOVERY_REPLICA_ID_TARGET_SERVICE_PROGRESS,
  PRIORITY_RECOVERY_REQUIRED_DISTINCT_NODE_COUNT,
  PRIORITY_RECOVERY_SAMPLE_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_SAMPLE_PUBLICATION_EPOCH,
  PRIORITY_RECOVERY_SEMANTIC_STATE_BLOCKED_UNCLASSIFIED,
  PRIORITY_RECOVERY_SEMANTIC_STATE_CONVERGED,
  PRIORITY_RECOVERY_SEMANTIC_STATE_COORDINATION_MISMATCH,
  PRIORITY_RECOVERY_SEMANTIC_STATE_LEARNER_PROMOTION_BLOCKED,
  PRIORITY_RECOVERY_SEMANTIC_STATE_NEEDS_OPERATION,
  PRIORITY_RECOVERY_SEMANTIC_STATE_OPERATION_STALLED,
  PRIORITY_RECOVERY_SEMANTIC_STATE_RECOVERING_IN_FLIGHT,
  PRIORITY_RECOVERY_SEMANTIC_STATE_SPREAD_SATISFIED_IN_FLIGHT,
  PRIORITY_RECOVERY_SERIAL_WAIT_BLOCKING_OPERATION_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_BLOCKING_PARTITION_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_OPERATION_IDS_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_PROGRESS_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_RELEASE_TEST_NAME,
  PRIORITY_RECOVERY_SERIAL_WAIT_WITNESS_ID_MESSAGE,
  PRIORITY_RECOVERY_SERIAL_WAIT_WITNESS_TEST_NAME,
  PRIORITY_RECOVERY_SINGLE_ADD_BUDGET_LIMIT,
  PRIORITY_RECOVERY_SINGLE_EMERGENCY_BUDGET_LIMIT,
  PRIORITY_RECOVERY_SINGLE_EMERGENCY_OVERFLOW_SLOT_COUNT,
  PRIORITY_RECOVERY_SINGLE_OPERATION_COUNT,
  PRIORITY_RECOVERY_SINGLE_PRIORITY_IN_FLIGHT_COUNT,
  PRIORITY_RECOVERY_SINGLE_SPREAD_GAP,
  PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_FAILED_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_PARTITION_ID,
  PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_REPLACEMENT_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_TRANSACTION_PARTICIPANTS_STALE_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_TRANSACTIONS_REPLACEMENT_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_TRANSACTIONS_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_WRITE_COMPLETED_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_WRITE_CREATING_REPLICA_ID,
  PRIORITY_RECOVERY_SQL_WRITE_OPERATIONS_PARTITION_ID,
  PRIORITY_RECOVERY_STALE_OPERATION_PROGRESS_AT_MS,
  PRIORITY_RECOVERY_STALE_READY_DISTINCT_NODE_COUNT,
  PRIORITY_RECOVERY_STALE_SERIAL_WAIT_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_MESSAGE,
  PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_PROGRESS_MESSAGE,
  PRIORITY_RECOVERY_STALE_SERIAL_WAIT_RELEASE_TEST_NAME,
  PRIORITY_RECOVERY_STATUS_ACTIVE,
  PRIORITY_RECOVERY_STATUS_COMPLETED,
  PRIORITY_RECOVERY_STATUS_CREATING,
  PRIORITY_RECOVERY_STATUS_FAILED,
  PRIORITY_RECOVERY_STATUS_PENDING,
  PRIORITY_RECOVERY_STATUS_REMOVED,
  PRIORITY_RECOVERY_STATUS_SYNCING,
  PRIORITY_RECOVERY_SUPERSEDED_OPERATION_UPDATED_AT_MS,
  PRIORITY_RECOVERY_TARGET_SERVICE_CAPTURED_AT_MS,
  PRIORITY_RECOVERY_TARGET_SERVICE_PROGRESS_AT_MS,
  PRIORITY_RECOVERY_TARGET_VISIBILITY_ACTIVE_OPERATIONAL,
  PRIORITY_RECOVERY_TERMINAL_REPLACE_OPERATION_CONTEXT,
  PRIORITY_RECOVERY_TOTAL_PRIORITY_PARTITION_COUNT,
  PRIORITY_RECOVERY_VISIBILITY_STATE_CACHE_VISIBLE,
  PRIORITY_RECOVERY_WORKFLOW_STATE_IN_FLIGHT,
  PRIORITY_RECOVERY_WORKFLOW_STATE_REMOVE_PHASE,
  PRIORITY_RECOVERY_WORKFLOW_STEP_ACTIVE,
  PRIORITY_RECOVERY_WORKFLOW_STEP_CREATING,
  PRIORITY_RECOVERY_WORKFLOW_STEP_FAILED,
  PRIORITY_RECOVERY_WORKFLOW_STEP_PENDING,
  PRIORITY_RECOVERY_WORKFLOW_STEP_REMOVED,
  PRIORITY_RECOVERY_WORKFLOW_STEP_SENDING,
  PRIORITY_RECOVERY_WORKFLOW_STEP_SYNCING,
  PUBLICATION_PRIORITY_PARTITION_ID,
  REPLICA_OPERATION_PRIORITY_PARTITION_ID,
  resolvePriorityRecoveryAdmissionPlanFromPublication,
  resolveTrackedPriorityRecoveryAdmissionPlan,
  SQL_TRANSACTION_PRIORITY_PARTITION_ID,
  test,
};

registerPriorityRecoverySnapshotCore01Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore02Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore03Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore04Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore05Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore06Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore07Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotCore08Tests(priorityRecoverySnapshotTestContext);
registerPriorityRecoverySnapshotSupplementalTests(
  priorityRecoverySnapshotTestContext,
);
