/**
 * Property Test: Structured Logging Consistency
 * **Property 19: Structured Logging Consistency**
 * **Validates: Requirements 16.1, 16.4**
 *
 * *For any* log entry generated by the system, it should use the designated
 * logging library and include consistent structured metadata (node_id,
 * service_id, timestamp).
 *
 * This property test verifies that:
 * 1. All log entries include required metadata fields
 * 2. Log entries are consistently structured across all log levels
 * 3. Metadata is preserved through child loggers
 */

import {test} from 'tap';
import fc from 'fast-check';
import {LoggingService, LOG_LEVELS} from '../../src/logging/logging-service.js';
import {ConfigurationManager} from '../../src/config/configuration-manager.js';

// Initialize configuration before tests
test('setup', async (t) => {
  ConfigurationManager.resetInstance();
  const config = ConfigurationManager.getInstance();
  config.initialize({node: {id: 'property-test-node'}});
  t.pass('configuration initialized');
});

test('Property 19: Structured Logging Consistency', async (t) => {
  /**
   * Property: For any log message and context, the log entry should
   * include consistent structured metadata.
   */
  t.test('log entries include required metadata', async (t) => {
    fc.assert(
      fc.property(
        fc.constantFrom(...LOG_LEVELS.filter((l) => l !== 'fatal')),
        fc.string({minLength: 1, maxLength: 100}),
        fc.record({
          serviceId: fc.option(fc.uuid(), {nil: undefined}),
          serviceType: fc.option(
            fc.constantFrom('partition', 'message_group', 'node'),
            {nil: undefined},
          ),
          traceId: fc.option(fc.uuid(), {nil: undefined}),
        }),
        (level, message, context) => {
          LoggingService.resetInstance();
          const logger = LoggingService.getInstance();
          logger.initialize({nodeId: 'test-node', level: 'trace'});

          // Log the message
          logger[level](message, context);

          // Get the buffered entry
          const entry = logger.buffer[0];

          // Verify required fields
          const hasLogId = typeof entry.logId === 'string' && entry.logId.length > 0;
          const hasTimestamp = typeof entry.timestamp === 'number' && entry.timestamp > 0;
          const hasLevel = typeof entry.level === 'string' &&
            LOG_LEVELS.map((l) => l.toUpperCase()).includes(entry.level);
          const hasNodeId = entry.nodeId === 'test-node';
          const hasMessage = entry.message === message;
          const hasCreatedAt = typeof entry.createdAt === 'number';

          LoggingService.resetInstance();

          return hasLogId && hasTimestamp && hasLevel &&
                 hasNodeId && hasMessage && hasCreatedAt;
        },
      ),
      {numRuns: 10},
    );

    t.pass('all log entries include required metadata');
  });

  /**
   * Property: For any log level, the entry structure should be consistent.
   */
  t.test('log structure is consistent across all levels', async (t) => {
    fc.assert(
      fc.property(
        fc.constantFrom(...LOG_LEVELS.filter((l) => l !== 'fatal')),
        fc.string({minLength: 1, maxLength: 50}),
        (level, message) => {
          LoggingService.resetInstance();
          const logger = LoggingService.getInstance();
          logger.initialize({nodeId: 'test-node', level: 'trace'});

          logger[level](message);

          const entry = logger.buffer[0];

          // All entries should have the same structure
          const requiredKeys = [
            'logId', 'timestamp', 'level', 'nodeId', 'subsystem',
            'serviceId', 'serviceType', 'message',
            'traceId', 'metadata', 'createdAt',
          ];

          const hasAllKeys = requiredKeys.every((key) => key in entry);
          const levelMatches = entry.level === level.toUpperCase();

          LoggingService.resetInstance();

          return hasAllKeys && levelMatches;
        },
      ),
      {numRuns: 10},
    );

    t.pass('log structure is consistent across all levels');
  });

  /**
   * Property: For any child logger bindings, the metadata should be
   * preserved in all log entries.
   */
  t.test('child logger preserves metadata', async (t) => {
    fc.assert(
      fc.property(
        fc.uuid(),
        fc.constantFrom('partition', 'message_group', 'node'),
        fc.string({minLength: 1, maxLength: 50}),
        (serviceId, serviceType, message) => {
          LoggingService.resetInstance();
          const logger = LoggingService.getInstance();
          logger.initialize({nodeId: 'test-node', level: 'trace'});

          const childLogger = logger.child({serviceId, serviceType});
          childLogger.info(message);

          const entry = logger.buffer[0];

          const hasServiceId = entry.metadata.serviceId === serviceId;
          const hasServiceType = entry.metadata.serviceType === serviceType;

          LoggingService.resetInstance();

          return hasServiceId && hasServiceType;
        },
      ),
      {numRuns: 10},
    );

    t.pass('child logger preserves metadata in all entries');
  });

  /**
   * Property: For any nested child loggers, all bindings should be merged.
   */
  t.test('nested child loggers merge bindings', async (t) => {
    fc.assert(
      fc.property(
        fc.uuid(),
        fc.uuid(),
        fc.string({minLength: 1, maxLength: 50}),
        (serviceId, traceId, message) => {
          LoggingService.resetInstance();
          const logger = LoggingService.getInstance();
          logger.initialize({nodeId: 'test-node', level: 'trace'});

          const child1 = logger.child({serviceId});
          const child2 = child1.child({traceId});
          child2.info(message);

          const entry = logger.buffer[0];

          const hasServiceId = entry.metadata.serviceId === serviceId;
          const hasTraceId = entry.metadata.traceId === traceId;

          LoggingService.resetInstance();

          return hasServiceId && hasTraceId;
        },
      ),
      {numRuns: 10},
    );

    t.pass('nested child loggers merge all bindings');
  });

  /**
   * Property: For any log entry, the timestamp should be monotonically
   * increasing within the same logger instance.
   */
  t.test('timestamps are monotonically increasing', async (t) => {
    fc.assert(
      fc.property(
        fc.array(fc.string({minLength: 1, maxLength: 20}), {minLength: 2, maxLength: 10}),
        (messages) => {
          LoggingService.resetInstance();
          const logger = LoggingService.getInstance();
          logger.initialize({nodeId: 'test-node', level: 'trace'});

          for (const msg of messages) {
            logger.info(msg);
          }

          const timestamps = logger.buffer.map((e) => e.timestamp);

          // Timestamps should be non-decreasing
          for (let i = 1; i < timestamps.length; i++) {
            if (timestamps[i] < timestamps[i - 1]) {
              LoggingService.resetInstance();
              return false;
            }
          }

          LoggingService.resetInstance();
          return true;
        },
      ),
      {numRuns: 10},
    );

    t.pass('timestamps are monotonically increasing');
  });
});

test('cleanup', async (t) => {
  LoggingService.resetInstance();
  ConfigurationManager.resetInstance();
  t.pass('cleanup complete');
});
