package lagrange:cell;

interface context {
  read: func(table: u32, key: u32) -> s32;
  write: func(table: u32, key: u32, value: s32);
  capability: func(capability: u32) -> s32;
}

world request-cell {
  import context;
  export run: func(request: string) -> string;
}
