const COLUMN = Object.freeze({
  NODE_ID: 'node_id',
  NODE_ADDRESS: 'node_address',
  CPU_CORES: 'cpu_cores',
  MEMORY_MB: 'memory_mb',
  DISK_GB: 'disk_gb',
  CPU_USAGE_PERCENT: 'cpu_usage_percent',
  MEMORY_USAGE_PERCENT: 'memory_usage_percent',
  DISK_USAGE_PERCENT: 'disk_usage_percent',
  STATUS: 'status',
  STATE: 'state',
  PARTITION_ID: 'partition_id',
  SIZE_BYTES: 'size_bytes',
  LEADER_NODE_ID: 'leader_node_id',
  // Local-only tenure claim annotations stamped by the owner-local canonical
  // leader projection (never durable columns, so a CDC round-trip of any
  // durable row cannot carry them — that asymmetry is the replay fence).
  LEADER_CLAIM_NODE_ID: 'leader_claim_node_id',
  LEADER_CLAIM_RAFT_TERM: 'leader_claim_raft_term',
  LEADER_CLAIM_MINTED_AGAINST_UPDATED_AT: 'leader_claim_minted_against_updated_at',
  TABLE_ID: 'table_id',
  SERVICE_ID: 'service_id',
  OPERATION_ID: 'operation_id',
  RESERVATION_ID: 'reservation_id',
  ENTITY_TYPE: 'entity_type',
  ENTITY_ID: 'entity_id',
  GROUP_ID: 'group_id',
  INDEX_ID: 'index_id',
  LOG_ID: 'log_id',
  CONFIG_KEY: 'config_key',
  CONFIG_VALUE: 'config_value',
  VALUE_TYPE: 'value_type',
  REQUIRES_RESTART: 'requires_restart',
  DESCRIPTION: 'description',
  DEFAULT_VALUE: 'default_value',
  UPDATED_BY: 'updated_by',
  UPDATED_AT: 'updated_at',
  UPDATED_AT_HLC: 'updated_at_hlc',
  CREATED_AT: 'created_at',
  QUERY_ID: 'query_id',
  CONTEXT_ID: 'context_id',
  FUNCTION_ID: 'function_id',
  ADDRESS: 'address',
  REPLICA_ID: 'replica_id',
  CONNECTION_STATE: 'connection_state',
  CAPABILITIES: 'capabilities',
  LAST_HEARTBEAT: 'last_heartbeat',
  BOOT_INCARNATION: 'boot_incarnation',
  READY_LEASE_EXPIRES_AT: 'ready_lease_expires_at',
  STORAGE_BUDGET_BYTES: 'storage_budget_bytes',
  STORAGE_BUDGET_SOURCE: 'storage_budget_source',
  STORAGE_BUDGET_UPDATED_AT: 'storage_budget_updated_at',
  LATENCY_GROUP_ID: 'latency_group_id',
  LAST_LATENCY_CHECK_AT: 'last_latency_check_at',
  LATENCY_ASSIGNMENT_STATE: 'latency_assignment_state',
  SERVICE_TYPE: 'service_type',
  RAFT_ROLE: 'raft_role',
  TARGET_NODE_ID: 'target_node_id',
  ESTIMATED_BYTES: 'estimated_bytes',
  AMPLIFICATION_FACTOR: 'amplification_factor',
  EXPIRES_AT: 'expires_at',
  RELEASED_AT: 'released_at',
  REASON_CODE: 'reason_code',
  // Endpoint columns for node_endpoints table
  ENDPOINT_ID: 'endpoint_id',
  TRANSPORT_TYPE: 'transport_type',
  PRIORITY: 'priority',
  METADATA: 'metadata',
  // Timer columns for service_timers table
  TIMER_ID: 'timer_id',
  // WASM meta-service columns
  NAMESPACE: 'namespace',
  NAME: 'name',
  VERSION: 'version',
  LOCK_ID: 'lock_id',
  TENANT_ID: 'tenant_id',
  IDEMPOTENCY_KEY: 'idempotency_key',
  REPRESENTATIVE_NODE_ID: 'representative_node_id',
  COORDINATOR_NODE_ID: 'coordinator_node_id',
  SOURCE_GROUP_ID: 'source_group_id',
  TARGET_GROUP_ID: 'target_group_id',
  LATENCY_MS: 'latency_ms',
  SAMPLE_COUNT: 'sample_count',
  SAMPLE_QUALITY: 'sample_quality',
  LAST_MEASURED_AT: 'last_measured_at',
  LATENCY_EDGE_ID: 'latency_edge_id',
});

export {COLUMN};
