const TABLES = Object.freeze({
  NODES: 'nodes',
  PARTITIONS: 'partitions',
  SERVICES: 'services',
  MESSAGE_GROUPS: 'message_groups',
  REPLICA_OPERATIONS: 'replica_operations',
  INDICES: 'indices',
  LOGS: 'logs',
  CONFIG: 'config',
  LIVE_QUERIES: 'live_queries',
  CONTEXTS: 'contexts',
  CODE: 'code',
  CONTROL_PLANE_PUBLICATIONS: 'control_plane_publications',
  TABLES: 'tables',
  SCHEMA_MIGRATIONS: 'schema_migrations',
  SCHEMA_MIGRATION_PARTITIONS: 'schema_migration_partitions',
  NODE_ENDPOINTS: 'node_endpoints',
  SERVICE_DEFINITIONS: 'service_definitions',
  SERVICE_ENDPOINTS: 'service_endpoints',
  SERVICE_TIMERS: 'service_timers',
  MODULE_MANIFESTS: 'module_manifests',
  PACKAGE_REGISTRY_MAPPINGS: 'package_registry_mappings',
  PACKAGE_REGISTRY_OVERRIDES: 'package_registry_overrides',
  MODULE_DEPENDENCY_LOCKS: 'module_dependency_locks',
  WASM_OPERATIONS: 'wasm_operations',
  SQL_TRANSACTIONS: 'sql_transactions',
  SQL_TRANSACTION_PARTICIPANTS: 'sql_transaction_participants',
  SQL_WRITE_OPERATIONS: 'sql_write_operations',
  DEBUG_SESSIONS: 'debug_sessions',
  DEBUG_BREAKPOINTS: 'debug_breakpoints',
  DEBUG_SNAPSHOTS: 'debug_snapshots',
  STORAGE_RESERVATIONS: 'storage_reservations',
  LATENCY_GROUPS: 'latency_groups',
  INTER_GROUP_LATENCIES: 'inter_group_latencies',
});

export {TABLES};
