// Canonical owner for shared test-output path and suffix constants.
const TEST_OUTPUT_ROOT_DIR = 'test-output';
const TEST_OUTPUT_REPORTS_DIR = 'reports';
const TEST_OUTPUT_PLAYBACK_DIR = '.playback';
const TEST_OUTPUT_RUN_METADATA_DIR = '.run-metadata';
const TEST_OUTPUT_EXAMPLES_DIR = 'examples';
const TEST_OUTPUT_SUFFIX_JSON = '.json';
const TEST_OUTPUT_SUFFIX_REPORT = '.report.json';

const TEST_OUTPUT_PATH = Object.freeze({
  ROOT: TEST_OUTPUT_ROOT_DIR,
  REPORTS_DIR: TEST_OUTPUT_REPORTS_DIR,
  PLAYBACK_DIR: TEST_OUTPUT_PLAYBACK_DIR,
  RUN_METADATA_DIR: TEST_OUTPUT_RUN_METADATA_DIR,
  EXAMPLES_DIR: TEST_OUTPUT_EXAMPLES_DIR,
});

const TEST_OUTPUT_SUFFIX = Object.freeze({
  JSON: TEST_OUTPUT_SUFFIX_JSON,
  REPORT: TEST_OUTPUT_SUFFIX_REPORT,
});

export {
  TEST_OUTPUT_EXAMPLES_DIR,
  TEST_OUTPUT_PATH,
  TEST_OUTPUT_PLAYBACK_DIR,
  TEST_OUTPUT_REPORTS_DIR,
  TEST_OUTPUT_ROOT_DIR,
  TEST_OUTPUT_RUN_METADATA_DIR,
  TEST_OUTPUT_SUFFIX,
  TEST_OUTPUT_SUFFIX_JSON,
  TEST_OUTPUT_SUFFIX_REPORT,
};
