const TRANSACTION_MODE = Object.freeze({
  AUTOCOMMIT: 'AUTOCOMMIT',
  EXPLICIT: 'EXPLICIT',
});

const PARTICIPANT_SET_STATE = Object.freeze({
  OPEN: 'OPEN',
  FROZEN: 'FROZEN',
});

const COMMIT_MODE = Object.freeze({
  NOT_SELECTED: 'NOT_SELECTED',
  ONE_PHASE_COMMIT: 'ONE_PHASE_COMMIT',
  TWO_PHASE_COMMIT: 'TWO_PHASE_COMMIT',
});

const PARTICIPANT_COMMIT_OUTCOME = Object.freeze({
  COMMITTED: 'COMMITTED',
  NOT_COMMITTED: 'NOT_COMMITTED',
  UNKNOWN: 'UNKNOWN',
});

export {
  COMMIT_MODE,
  PARTICIPANT_COMMIT_OUTCOME,
  PARTICIPANT_SET_STATE,
  TRANSACTION_MODE,
};
