const WORKFLOW_STEP = Object.freeze({
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  CREATING: 'CREATING',
  SYNCING: 'SYNCING',
  ACTIVE: 'ACTIVE',
  STOPPING: 'STOPPING',
  REMOVED: 'REMOVED',
  FAILED: 'FAILED',
});

export {WORKFLOW_STEP};
