{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagrange-endpoint-sync-controller.fullname" . }}
  labels:
    {{- include "lagrange-endpoint-sync-controller.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "lagrange-endpoint-sync-controller.selectorLabels" . | nindent 4 }}
{{- end }}
