#!/usr/bin/env node
/**
 * Build script for creating bundled JavaScript files for SEA packaging.
 * Uses esbuild to bundle all dependencies into single files.
 *
 * Note: Native modules (better-sqlite3, piscina) are marked as external
 * and must be available at runtime. For full standalone deployment,
 * these modules need to be bundled separately or the system needs
 * Node.js with these modules installed.
 */

import * as esbuild from 'esbuild';
import {fileURLToPath} from 'url';
import {dirname, join} from 'path';
import {mkdirSync, existsSync} from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

/**
 * Native modules that cannot be bundled and must be available at runtime.
 * These are excluded from the bundle.
 */
const NATIVE_MODULES = [
  'better-sqlite3',
  'piscina',
];

/**
 * Build a bundle for SEA packaging.
 * @param {string} entryPoint - Entry point file path
 * @param {string} outputFile - Output bundle file path
 * @param {string} name - Bundle name for logging
 */
async function buildBundle(entryPoint, outputFile, name) {
  console.log(`Building ${name} bundle...`);

  const startTime = Date.now();

  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    platform: 'node',
    target: 'node22',
    outfile: outputFile,
    format: 'cjs',
    external: NATIVE_MODULES,
    minify: true,
    sourcemap: false,
    treeShaking: true,
    define: {
      'process.env.SEA_BUILD': '"true"',
    },
    banner: {
      js: '// Single Executable Application Bundle\n' +
          '// Generated by build-sea.js\n' +
          '// Native modules required at runtime: ' + NATIVE_MODULES.join(', ') + '\n',
    },
  });

  const duration = Date.now() - startTime;
  console.log(`  ✓ ${name} bundle created in ${duration}ms`);
}

/**
 * Main build function.
 */
async function main() {
  console.log('=== Building SEA Bundles ===\n');

  const distDir = join(projectRoot, 'dist');
  if (!existsSync(distDir)) {
    mkdirSync(distDir, {recursive: true});
    console.log('Created dist directory\n');
  }

  try {
    await buildBundle(
        join(projectRoot, 'src/sea-entry.js'),
        join(distDir, 'index.bundle.cjs'),
        'Main System',
    );

    await buildBundle(
        join(projectRoot, 'src/cli/bin/ddb-admin.js'),
        join(distDir, 'admin-cli.bundle.cjs'),
        'Admin CLI',
    );

    console.log('\n=== Build Complete ===');
    console.log('Bundles created in dist/');
    console.log('  - index.bundle.cjs (Main System)');
    console.log('  - admin-cli.bundle.cjs (Admin CLI)');
    console.log('\nNote: Native modules must be available at runtime:');
    NATIVE_MODULES.forEach((mod) => console.log(`  - ${mod}`));
  } catch (error) {
    console.error('\nBuild failed:', error.message);
    process.exit(1);
  }
}

main();
