#!/usr/bin/env node
/**
 * Build script for creating bundled JavaScript files for SEA packaging.
 * Uses esbuild to bundle the runtime entrypoints and stages filesystem-backed
 * dependencies required by worker threads and native addons.
 *
 * The main SEA/runtime bundle still needs selected files on disk:
 * - better-sqlite3 and its runtime helpers
 * - piscina and its internal worker bootstrap
 * - bundled worker entrypoints for replica/service pools
 */

import * as esbuild from 'esbuild';
import {fileURLToPath} from 'url';
import {dirname, join} from 'path';
import {cpSync, existsSync, mkdirSync, rmSync} from 'fs';

const LOCAL_STR_NODE = 'node';
const LOCAL_STR_NODE22 = 'node22';
const LOCAL_STR_DIST = 'dist';
const LOCAL_STR_CJS = 'cjs';
const LOCAL_STR_TRUE = '"true"';
const LOCAL_STR_BUILDING_SEA_BUNDLES = '=== Building SEA Bundles ===\n';
const LOCAL_STR_CREATED_DIST_DIRECTORY = 'Created dist directory\n';
const LOCAL_STR_STAGING_RUNTIME_DEPENDENCIES = '\nStaging runtime dependencies...';
const LOCAL_STR_BUILD_COMPLETE = '\n=== Build Complete ===';
const LOCAL_STR_BUNDLES_CREATED_IN_DIST = 'Bundles created in dist/';
const LOCAL_STR_NODE_MODULES_RUNTIME_DEPENDENCIES = '  - node_modules/ (runtime dependencies)';
const LOCAL_STR_BUILD_FAILED = '\nBuild failed:';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

const BUILD_BANNER = [
  '// Single Executable Application Bundle',
  '// Generated by build-sea.js',
  'require = require(\'node:module\').createRequire(__filename);',
  '',
].join('\n');

const MAIN_RUNTIME_EXTERNALS = [
  'better-sqlite3',
  'piscina',
];

const CLI_RUNTIME_EXTERNALS = [
  'blessed',
];

const BUNDLES = [
  {
    entryPoint: join(projectRoot, 'src/sea-entry.js'),
    outputFile: 'index.bundle.cjs',
    name: 'Main System',
    external: MAIN_RUNTIME_EXTERNALS,
  },
  {
    entryPoint: join(projectRoot, 'src/cli/bin/ddb-admin.js'),
    outputFile: 'admin-cli.bundle.cjs',
    name: 'Admin CLI',
    external: CLI_RUNTIME_EXTERNALS,
  },
  {
    entryPoint: join(projectRoot, 'src/threading/service-worker.js'),
    outputFile: 'service-worker.bundle.cjs',
    name: 'Service Worker',
    external: MAIN_RUNTIME_EXTERNALS,
  },
  {
    entryPoint: join(projectRoot, 'src/worker/replica-worker.js'),
    outputFile: 'replica-worker.bundle.cjs',
    name: 'Replica Worker',
    external: MAIN_RUNTIME_EXTERNALS,
  },
];

const RUNTIME_PACKAGES = [
  'better-sqlite3',
  'bindings',
  'blessed',
  'file-uri-to-path',
  'piscina',
];

/**
 * Build a bundle for SEA packaging.
 * @param {string} entryPoint - Entry point file path
 * @param {string} outputFile - Output bundle basename
 * @param {string} name - Bundle name for logging
 * @param {string[]} external - External packages
 */
async function buildBundle(entryPoint, outputFile, name, external) {
  console.log(`Building ${name} bundle...`);

  const startTime = Date.now();

  await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    platform: LOCAL_STR_NODE,
    target: LOCAL_STR_NODE22,
    outfile: join(projectRoot, LOCAL_STR_DIST, outputFile),
    format: LOCAL_STR_CJS,
    external,
    minify: true,
    sourcemap: false,
    treeShaking: true,
    define: {
      'process.env.SEA_BUILD': LOCAL_STR_TRUE,
    },
    banner: {
      js: BUILD_BANNER,
    },
  });

  const duration = Date.now() - startTime;
  console.log(`  ✓ ${name} bundle created in ${duration}ms`);
}

/**
 * Stage filesystem-backed runtime packages beside the bundled output.
 */
function stageRuntimePackages() {
  const runtimeNodeModulesDir = join(projectRoot, 'dist', 'node_modules');
  rmSync(runtimeNodeModulesDir, {recursive: true, force: true});
  mkdirSync(runtimeNodeModulesDir, {recursive: true});

  for (const packageName of RUNTIME_PACKAGES) {
    const sourceDir = join(projectRoot, 'node_modules', packageName);
    const targetDir = join(runtimeNodeModulesDir, packageName);
    cpSync(sourceDir, targetDir, {recursive: true});
    console.log(`  ✓ staged runtime package ${packageName}`);
  }
}

/**
 * Main build function.
 */
async function main() {
  console.log(LOCAL_STR_BUILDING_SEA_BUNDLES);

  const distDir = join(projectRoot, 'dist');
  if (!existsSync(distDir)) {
    mkdirSync(distDir, {recursive: true});
    console.log(LOCAL_STR_CREATED_DIST_DIRECTORY);
  }

  try {
    for (const bundle of BUNDLES) {
      await buildBundle(
        bundle.entryPoint,
        bundle.outputFile,
        bundle.name,
        bundle.external,
      );
    }

    console.log(LOCAL_STR_STAGING_RUNTIME_DEPENDENCIES);
    stageRuntimePackages();

    console.log(LOCAL_STR_BUILD_COMPLETE);
    console.log(LOCAL_STR_BUNDLES_CREATED_IN_DIST);
    for (const bundle of BUNDLES) {
      console.log(`  - ${bundle.outputFile} (${bundle.name})`);
    }
    console.log(LOCAL_STR_NODE_MODULES_RUNTIME_DEPENDENCIES);
  } catch (error) {
    console.error(LOCAL_STR_BUILD_FAILED, error.message);
    process.exit(1);
  }
}

// Top-level await, not fire-and-forget: importers (the packaging smoke test
// runs this via a worker-thread dynamic import) must observe completion of
// the build when the module settles, or they race the in-flight esbuild
// writes and see partially written dist/ output.
await main();
