#!/usr/bin/env node

// Per-release notes renderer: makes CHANGELOG.md the single source of the
// "what changed in this release" prose on every release surface.
//
// release.yml runs this FIRST (fail-fast, before the 40-60min test:ci gate):
//   --mode check     validates the tagged version has a non-empty CHANGELOG
//                    section AND matches package.json's version. A tag whose
//                    changes were never written down fails the release in
//                    seconds, not after the full gate.
//   --mode notes     prints the GitHub release-page body: the
//                    version's changelog section + image references + links.
//   --mode overview  prints docs/dockerhub-overview.md with a generated
//                    "Release notes" section (every released version, newest
//                    first) injected between the RELEASE-NOTES markers; the
//                    workflow PATCHes the result to Docker Hub's repository
//                    full_description. Docker Hub has no per-tag prose surface,
//                    so the repo page carries the per-release history and the
//                    OCI image labels carry per-tag provenance.
//
// Section grammar (Keep a Changelog): `## [x.y.z] — YYYY-MM-DD` headings,
// `## [Unreleased]` excluded, trailing `[ref]: url` link-definition block
// trimmed. Docker Hub caps full_description at 25,000 bytes: older versions
// degrade to link-only lines (newest-first bodies kept) before any truncation.

import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join, resolve} from 'node:path';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, '..');
const CHANGELOG_PATH = join(REPO_ROOT, 'CHANGELOG.md');
const OVERVIEW_PATH = join(REPO_ROOT, 'docs/dockerhub-overview.md');
const PACKAGE_JSON_PATH = join(REPO_ROOT, 'package.json');
const CHART_PATH = join(REPO_ROOT, 'charts/lagrange-node/Chart.yaml');

const REPO_URL = 'https://github.com/psvensson/lagrange';
const DOCKERHUB_URL = 'https://hub.docker.com/r/psvensson/lagrange';
const DOCKERHUB_IMAGE = 'docker.io/psvensson/lagrange';

export const OVERVIEW_MARKER_BEGIN =
  '<!-- RELEASE-NOTES:BEGIN — generated by scripts/release-notes.js from CHANGELOG.md; do not edit between markers -->';
export const OVERVIEW_MARKER_END = '<!-- RELEASE-NOTES:END -->';

// Docker Hub rejects full_description above 25,000 (bytes, conservatively —
// measured as UTF-8, not UTF-16 code units, so multibyte prose can't sneak past).
export const DOCKERHUB_DESCRIPTION_MAX_BYTES = 25000;

const SECTION_HEADING_PATTERN = /^## \[([^\]]+)\](?:\s*[—–-]+\s*(.*))?\s*$/u;
const LINK_DEFINITION_PATTERN = /^\[[^\]]+\]:\s+\S+\s*$/u;
const CODE_FENCE_PATTERN = /^\s*(```|~~~)/u;
const CHART_VERSION_PATTERN = /^version:\s*"?([^"\s#]+)"?\s*$/mu;
const CHART_APP_VERSION_PATTERN = /^appVersion:\s*"?([^"\s#]+)"?\s*$/mu;

function releasePageUrl(version) {
  return `${REPO_URL}/releases/tag/v${version}`;
}

export function assertReleaseVersions(version, packageVersion, chartText) {
  const chartVersion = CHART_VERSION_PATTERN.exec(chartText)?.[1] || '';
  const chartAppVersion = CHART_APP_VERSION_PATTERN.exec(chartText)?.[1] || '';
  const mismatches = [
    ['package.json', packageVersion],
    ['Chart.yaml version', chartVersion],
    ['Chart.yaml appVersion', chartAppVersion],
  ].filter(([, actual]) => actual !== version);
  if (mismatches.length > 0) {
    const details = mismatches
      .map(([source, actual]) => `${source}=${actual || '(missing)'}`)
      .join(', ');
    throw new Error(
      `Tag version ${version} does not match release metadata: ${details}.`,
    );
  }
}

/**
 * Parse every released section out of a Keep-a-Changelog document.
 * Returns [{version, date, body}] in file order (newest first).
 * `[Unreleased]` is skipped; trailing link-definition lines are trimmed.
 */
export function extractReleasedSections(changelogText) {
  const lines = changelogText.split('\n');
  const sections = [];
  let current = null;

  const finish = () => {
    if (!current) {
      return;
    }
    while (
      current.bodyLines.length > 0 &&
      (LINK_DEFINITION_PATTERN.test(current.bodyLines.at(-1)) ||
        current.bodyLines.at(-1).trim() === '')
    ) {
      current.bodyLines.pop();
    }
    sections.push({
      version: current.version,
      date: current.date,
      body: current.bodyLines.join('\n').trim(),
    });
    current = null;
  };

  let inFence = false;
  for (const line of lines) {
    if (CODE_FENCE_PATTERN.test(line)) {
      inFence = !inFence;
    }
    const match = inFence ? null : SECTION_HEADING_PATTERN.exec(line);
    if (match) {
      finish();
      const [, version, date] = match;
      if (version.toLowerCase() !== 'unreleased') {
        current = {version, date: date ? date.trim() : '', bodyLines: []};
      }
      continue;
    }
    if (current) {
      current.bodyLines.push(line);
    }
  }
  finish();
  return sections;
}

/**
 * The one version's section, or throw — a release tag without a written,
 * non-empty changelog section is a release-gate failure, not a soft default.
 */
export function extractChangelogSection(changelogText, version) {
  const section = extractReleasedSections(changelogText).find(
    (candidate) => candidate.version === version,
  );
  if (!section) {
    throw new Error(
      `CHANGELOG.md has no "## [${version}]" section. Move the [Unreleased] ` +
        'items under a dated section for this release before tagging.',
    );
  }
  if (section.body === '') {
    throw new Error(
      `CHANGELOG.md section "## [${version}]" is empty — a release must ` +
        'describe its changes.',
    );
  }
  return section;
}

/**
 * Demote every markdown heading in a section body by one level (### → ####),
 * leaving fenced code blocks alone (a `# comment` in a shell snippet is not a
 * heading).
 */
export function demoteHeadings(body) {
  let inFence = false;
  return body
    .split('\n')
    .map((line) => {
      if (CODE_FENCE_PATTERN.test(line)) {
        inFence = !inFence;
        return line;
      }
      return inFence ? line : line.replace(/^(#{1,5})(\s)/u, '#$1$2');
    })
    .join('\n');
}

/** The GitHub release-page body for one version. */
export function renderGitHubReleaseNotes(section) {
  const {version, date, body} = section;
  const dateSuffix = date ? ` — ${date}` : '';
  return [
    `Lagrange ${version}${dateSuffix} (experimental / alpha).`,
    '',
    body,
    '',
    '---',
    '',
    '**Docker images** (linux/amd64, distroless):',
    '',
    `- \`${DOCKERHUB_IMAGE}:${version}\` ([Docker Hub](${DOCKERHUB_URL}))`,
    '',
    `Full history: [CHANGELOG.md](${REPO_URL}/blob/v${version}/CHANGELOG.md)` +
      ` · process: [RELEASE.md](${REPO_URL}/blob/v${version}/RELEASE.md)`,
    '',
  ].join('\n');
}

function renderFullEntry(section) {
  const dateSuffix = section.date ? ` — ${section.date}` : '';
  return [
    `### ${section.version}${dateSuffix}`,
    '',
    demoteHeadings(section.body),
    '',
    `Artifacts and checksums: [release page](${releasePageUrl(section.version)}).`,
  ].join('\n');
}

// Link-only fallback for older versions under the char cap; the release page
// itself carries the full notes (rendered from the same changelog section).
function renderLinkEntry(section) {
  const dateSuffix = section.date ? ` (${section.date})` : '';
  return `- **${section.version}**${dateSuffix} — [release notes](${releasePageUrl(section.version)})`;
}

function renderNotesBlock(sections, fullBodyCount) {
  const blocks = sections.slice(0, fullBodyCount).map(renderFullEntry);
  const linkLines = sections.slice(fullBodyCount).map(renderLinkEntry);
  if (linkLines.length > 0) {
    blocks.push(linkLines.join('\n'));
  }
  return ['## Release notes', '', blocks.join('\n\n')].join('\n');
}

/**
 * The full Docker Hub overview: the committed template with the generated
 * release-notes block injected between the markers, held under maxBytes by
 * degrading oldest sections to link-only lines (never dropping a version).
 */
export function renderDockerhubOverview({
  template,
  sections,
  maxBytes = DOCKERHUB_DESCRIPTION_MAX_BYTES,
}) {
  const beginAt = template.indexOf(OVERVIEW_MARKER_BEGIN);
  const endAt = template.indexOf(OVERVIEW_MARKER_END);
  if (beginAt === -1 || endAt === -1 || endAt < beginAt) {
    throw new Error(
      'docs/dockerhub-overview.md is missing the RELEASE-NOTES:BEGIN/END ' +
        'marker pair the generated release-notes section is injected between.',
    );
  }
  if (sections.length === 0) {
    throw new Error('CHANGELOG.md contains no released sections to render.');
  }

  const inject = (block) =>
    template.slice(0, beginAt + OVERVIEW_MARKER_BEGIN.length) +
    '\n' +
    block +
    '\n' +
    template.slice(endAt);

  for (let fullBodyCount = sections.length; fullBodyCount >= 1; fullBodyCount--) {
    const rendered = inject(renderNotesBlock(sections, fullBodyCount));
    if (Buffer.byteLength(rendered, 'utf8') <= maxBytes) {
      return rendered;
    }
  }
  throw new Error(
    `Docker Hub overview exceeds ${maxBytes} bytes even with all but the ` +
      'newest release as link-only lines — shorten docs/dockerhub-overview.md ' +
      'or the newest changelog section.',
  );
}

function parseArgs(argv) {
  const args = {mode: null, version: null};
  for (let index = 0; index < argv.length; index++) {
    if (argv[index] === '--mode') {
      args.mode = argv[++index];
    } else if (argv[index] === '--version') {
      args.version = argv[++index];
    } else {
      throw new Error(`Unknown argument: ${argv[index]}`);
    }
  }
  if (!['check', 'notes', 'overview'].includes(args.mode)) {
    throw new Error('Usage: release-notes.js --mode check|notes|overview --version x.y.z');
  }
  if (!args.version) {
    throw new Error('--version is required (bare semver, no leading "v")');
  }
  if (args.version.startsWith('v')) {
    throw new Error(
      `--version takes the bare semver (got "${args.version}" — drop the leading "v")`,
    );
  }
  return args;
}

function runCli(argv) {
  const {mode, version} = parseArgs(argv);
  const changelogText = readFileSync(CHANGELOG_PATH, 'utf8');
  const section = extractChangelogSection(changelogText, version);

  if (mode === 'check') {
    const packageVersion = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8')).version;
    assertReleaseVersions(
      version,
      packageVersion,
      readFileSync(CHART_PATH, 'utf8'),
    );
    process.stdout.write(
      `ok: CHANGELOG.md has a non-empty [${version}] section and release versions match\n`,
    );
    return;
  }

  if (mode === 'notes') {
    process.stdout.write(renderGitHubReleaseNotes(section));
    return;
  }

  process.stdout.write(
    renderDockerhubOverview({
      template: readFileSync(OVERVIEW_PATH, 'utf8'),
      sections: extractReleasedSections(changelogText),
    }),
  );
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isMain) {
  try {
    runCli(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(`release-notes: ${error.message}\n`);
    process.exit(1);
  }
}
