#!/usr/bin/env node
// solve — CLI for the minimal autonomy-first solver.
//
// The registered subcommands are the keys of the COMMANDS map below. For the
// COMPLETE, always-current reference (purpose + usage for every subcommand), see
// the generated docs/steering/llm/solve-commands.md (regenerated by
// `npm run steering:llm:pack` from this file + docs/steering/solve-commands.json).
// Do not maintain a hand-curated list here — it drifts.
//
// The CLI is a thin shell over scripts/solve/*. All Quest truth lives in the
// append-only log; reports and state are projections.

import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

import {loadQuest, saveQuest, readLog, projectState, appendFinding, questFilePath,
  appendGuardOverride, appendReflection, readFindings, readRulesOutFindings}
  from './solve/store.js';
import {buildSealFreshnessAdvisory} from './solve/seal-freshness.js';
import {retreadCheckLines} from './solve/retread.js';
import {makeDryExecutor} from './solve/executor.js';
import {makeAgentExecutor} from './solve/agent-executor.js';
import {runLoop, runSupervised} from './solve/loop.js';
import {writeReport} from './solve/report.js';
import {runStep, stepAbort, stepPending} from './solve/step.js';
import {runNextCommand} from './solve/next.js';
import {buildDoctorReport, renderDoctor} from './solve/doctor.js';
import {
  QUEST_CLASS_PRODUCT,
  QUEST_CLASSES,
  SOLVE_DATA_DIR,
} from './solve/constants.js';
import {runTheoryCommand, theoryCommitArgs} from './solve/theory.js';
import {analyzeQuestHealth, renderHealth} from './solve/health.js';
import {buildAdvisories, renderAdvisoryLines} from './solve/advisories.js';
import {buildCurrentBlocker} from './solve/current-blocker.js';
import {analyzeScopePressure} from './solve/scope-pressure.js';
import {applyInheritedParentLinks, applySiblingSkeleton}
  from './solve/quest-derivation.js';
import {detectUnrecordedEvidence, ingestEvidence} from './solve/evidence.js';
import {runAttemptCommand} from './solve/attempt.js';
import {runAuditCommand} from './solve/audit.js';
import {runUpgradeCommand} from './solve/upgrade.js';
import {runReopenCommand} from './solve/reopen.js';
import {runParkCommand} from './solve/park.js';
import {runPortfolioCommand, buildPortfolio, loadAllQuests} from './solve/portfolio.js';
import {runMetaRatioCommand} from './solve/meta-ratio.js';
import {runMetaFrictionCommand} from './solve/meta-friction.js';
import {runCostCommand} from './solve/cost.js';
import {runAmendCommand} from './solve/amend.js';
import {runInheritCandidateCommand} from './solve/inherit-candidate.js';
import {
  runAttemptBaseCorrectionCommand,
} from './solve/attempt-base-correction.js';
import {runFrontierCommand, writeFrontier} from './solve/frontier.js';
import {runOverviewCommand, writeOverview} from './solve/overview.js';
import {runCheckpointCommand, runHandoffCommand} from './solve/handoff.js';
import {evaluate} from './solve/probe.js';
import {runInvariantsCommand, triggerOnTouchedOwner} from './solve/invariant-liveness.js';
import {scoreInvariants, renderInvariantBoard} from './solve/invariant-score.js';
import {
  CONTINUATION_BLOCKED_THEORY,
  CONTINUATION_BLOCKED_SCOPE,
  continuationOverridable,
} from './solve/continuation.js';
import {
  QUEST_AUTHORING_CONTRACT_VERSION,
  lintQuestCorpus,
  renderQuestLint,
} from './solve/quest-lint.js';
import {
  buildVerificationFinding,
  verificationState,
  VERIFICATION_CONTRACT_VERSION,
  VERIFICATION_SCOPE,
  VERIFIER_REJECTION_FINDING_KIND,
} from './solve/verification.js';
import {
  parseRejectionFindings,
  rejectionFindingBarProblem,
  REJECTION_FINDING_USAGE,
} from './solve/rejection-findings.js';
import {recordRejectionDecomposition} from './solve/rejection-decomposition.js';
import {
  continueQuestWorkflow,
  landQuestWorkflow,
  startQuestWorkflow,
} from './solve/operator-workflow.js';

const LOCAL_STR_OWNED_001 = 'new: Quest ID has append-only history but no Quest file; restore it or author a successor';
const LOCAL_STR_OWNED_002 = 'new: --force cannot overwrite a Quest with append-only history; author a successor';
const LOCAL_STR_OWNED_003 = 'roadmap-row';
const LOCAL_STR_OWNED_004 = 'spec-ref';
const LOCAL_STR_OWNED_005 = 'plan-doc';
const LOCAL_STR_OWNED_006 = 'closes-cl';
const LOCAL_STR_OWNED_007 = 'new: --parent-quest and --inherit-rulesout-from must name the same Quest';
const LOCAL_STR_OWNED_008 = 'lint: --id <questId> or --all is required';
const LOCAL_STR_OWNED_009 = 'pass';
const LOCAL_STR_OWNED_010 = ', ';

const INHERITED_RULESOUT_ABSENT_CLAIM = '(no claim)';
const INHERITED_RULESOUT_FINDING_KIND = 'inherited-rulesout';
const LINE_SEPARATOR = '\n';
const DRY_EXECUTOR_NOTICE =
  'run: default `dry` executor — a no-op skeleton that makes no real ' +
  'edits; real autonomous work needs --executor agent --yes\n';
const AUTO_DIFF_ARGUMENT = 'auto-diff';
const AUTO_DIFF_REQUIRES_COMMIT = 'step --auto-diff requires --commit';
const AUTO_DIFF_IGNORED_NOTICE =
  'step: --auto-diff ignored — an explicit --changeRef takes precedence\n';
const STEP_CHANGE_REF_REQUIRED =
  'step --commit requires --changeRef diff:<path> (or --auto-diff)';
const STEP_NEXT_ARGUMENTS =
  '--changeRef diff:<path> --summary "<what changed>" ' +
  '(--auto-diff snapshots the working tree as the changeRef)\n';
const NEXT_ID_REQUIRED = 'next: --id <questId> is required';
const COMMAND_SEPARATOR = '|';
const USAGE_ARGUMENTS = '[--id <questId>] [...]\n';

function parseArgs(argv) {
  const args = {_: []};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token.startsWith('--')) {
      const key = token.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith('--')) {
        args[key] = true;
      } else {
        if (args[key] === undefined) {
          args[key] = next;
        } else if (Array.isArray(args[key])) {
          args[key].push(next);
        } else {
          args[key] = [args[key], next];
        }
        i += 1;
      }
    } else {
      args._.push(token);
    }
  }
  return args;
}

function questTemplate(id, statement, questClass) {
  return {
    id,
    authoringContractVersion: QUEST_AUTHORING_CONTRACT_VERSION,
    verificationContractVersion: VERIFICATION_CONTRACT_VERSION,
    statement: statement || 'Describe the terminal success condition in one line.',
    priority: 1,
    // class: "product" (default) goals must be MEASURED against a real artifact;
    // "process" goals are scaffolding/decision records and may close on an oracle.
    // This drives report closure-strength labeling and the audit closure-mismatch warning.
    class: questClass || QUEST_CLASS_PRODUCT,
    // links situate the Quest in the planning graph. Readers keep the block
    // legacy-optional, while the versioned authoring contract requires a product
    // Quest to carry at least one recognized link before first declaration.
    links: {
      roadmapRow: null,
      specRef: null,
      closesCL: [],
      parentQuest: null,
      // planDoc: optional path to the epic/spec page carrying this Quest's intent
      // and rationale (e.g. "solve/epics/<id>.md"). Narrative belongs there, not in
      // the Quest; this is just the pointer.
      planDoc: null,
      // draftedAtCommit is only a freshness reference. The declaration event,
      // written by the first execution command after lint passes, is the seal.
      draftedAtCommit: null,
    },
    // done_when: the binary, artifact-bound success predicate. Sealed once declared.
    doneWhen: {
      probe: 'scenario-harness',
      args: {scenario: id, consecutive: 3, metric: 'priority'},
    },
    // frontiers: independent work surfaces. Each carries its own lower-is-better
    // metric (the progress gradient). The scheduler picks among open frontiers.
    frontiers: [
      {
        id: `${id}-main`,
        priority: 1,
        metric: {
          probe: 'scenario-harness',
          args: {scenario: id, metric: 'priority'},
        },
      },
    ],
    constraints: [
      {
        id: 'source-change-subagent-verification',
        statement: 'If this Quest changes source code, spawn a subagent verifier before audit and git handoff, then record a Solver finding with evidence subagent:<id>.',
      },
    ],
  };
}

// The commit the quest is sealed at, so the seal-freshness advisory can detect src/
// drift between the seal evidence and later work. Null outside a git work tree
// (unit-test tmpdirs) — readers already treat the links block as optional.
function resolveHeadCommit(root) {
  const out = spawnSync('git', ['rev-parse', 'HEAD'], {
    cwd: root,
    encoding: 'utf8',
  });
  if (out.status !== 0 || typeof out.stdout !== 'string') return null;
  const sha = out.stdout.trim();
  return /^[0-9a-f]{40}$/.test(sha) ? sha : null;
}

// Copy the parent quest's rulesOut findings onto the new quest as day-0 findings, so
// the lineage's already-refuted levers ride the existing finding/dossier machinery
// (statements stay a sealed result predicate; dead levers are findings, not prose).
function inheritRulesOutFindings(root, quest, parentId) {
  const frontier = quest.frontiers?.[0]?.id || `${quest.id}-main`;
  const seen = new Set();
  let copied = 0;
  for (const finding of readRulesOutFindings(root, parentId)) {
    if (seen.has(finding.rulesOut)) continue;
    seen.add(finding.rulesOut);
    appendFinding(root, quest.id, {
      frontier,
      claim: `inherited from ${parentId}: ${
        finding.claim || INHERITED_RULESOUT_ABSENT_CLAIM}`,
      kind: INHERITED_RULESOUT_FINDING_KIND,
      evidence: finding.evidence,
      rulesOut: finding.rulesOut,
    });
    copied += 1;
  }
  return copied;
}

// The declared quest class is real machinery (closure-kind, change-artifact scope
// classification, portfolio renderers), so it is settable at draft time instead of
// requiring a JSON edit after `new`. Anything but product|process is refused.
function resolveQuestClass(args) {
  if (args.class === undefined) return QUEST_CLASS_PRODUCT;
  if (!QUEST_CLASSES.includes(args.class)) {
    throw new Error(`new: --class must be one of ${QUEST_CLASSES.join('|')}`);
  }
  return args.class;
}

function cmdNew(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('new: --id <questId> is required');
  const file = questFilePath(root, id);
  // Quest identity is append-only even if its declarative JSON was deleted.
  // Inspect the log independently so deleting the draft cannot make an ID reusable.
  const existingLog = readLog(root, id);
  if (existingLog.length > 0 && !fs.existsSync(file)) {
    throw new Error(
      LOCAL_STR_OWNED_001,
    );
  }
  if (fs.existsSync(file) && !args.force) {
    throw new Error(`new: ${file} already exists (use --force to overwrite)`);
  }
  if (fs.existsSync(file) && args.force && existingLog.length > 0) {
    throw new Error(
      LOCAL_STR_OWNED_002,
    );
  }
  const quest = questTemplate(id, typeof args.statement === 'string' ?
    args.statement : null, resolveQuestClass(args));
  quest.links.draftedAtCommit = resolveHeadCommit(root);
  quest.links.roadmapRow = typeof args[LOCAL_STR_OWNED_003] === 'string' ?
    args[LOCAL_STR_OWNED_003] : null;
  quest.links.specRef = typeof args[LOCAL_STR_OWNED_004] === 'string' ?
    args[LOCAL_STR_OWNED_004] : null;
  quest.links.planDoc = typeof args[LOCAL_STR_OWNED_005] === 'string' ?
    args[LOCAL_STR_OWNED_005] : null;
  quest.links.closesCL = Array.isArray(args[LOCAL_STR_OWNED_006]) ?
    args[LOCAL_STR_OWNED_006] : (typeof args[LOCAL_STR_OWNED_006] === 'string' ?
      [args[LOCAL_STR_OWNED_006]] : []);
  const inheritedParentId = typeof args['inherit-rulesout-from'] === 'string' ?
    args['inherit-rulesout-from'] : null;
  const linkedParentId = typeof args['parent-quest'] === 'string' ?
    args['parent-quest'] : null;
  if (inheritedParentId && linkedParentId && inheritedParentId !== linkedParentId) {
    throw new Error(
      LOCAL_STR_OWNED_007,
    );
  }
  const siblingId = typeof args.from === 'string' ? args.from : null;
  const parentId = inheritedParentId || linkedParentId || siblingId;
  if (parentId) {
    const parent = loadQuest(root, parentId); // Fail before writing anything.
    quest.links.parentQuest = parentId;
    applyInheritedParentLinks(quest, parent);
    if (siblingId) {
      applySiblingSkeleton(quest, parent, {
        statement: args.statement,
        classExplicit: args.class !== undefined,
      });
    }
  }
  const written = saveQuest(root, quest);
  const inherited = inheritedParentId ?
    inheritRulesOutFindings(root, quest, inheritedParentId) : 0;
  const inheritedLine = inherited ?
    `inherited ${inherited} rulesOut finding(s) from ${inheritedParentId}\n` : '';
  if (!args.quiet) {
    process.stdout.write(
      `created ${written}\n${inheritedLine}` +
      `Edit it, then: node scripts/solve.js next --id ${id}\n`);
  }
  emitRetreadWarnings(root, quest);
  refreshFrontierBoard(root);
  return {quest, written, inherited};
}

function renderFacadeResult(command, result) {
  const next = result.next?.action || result.next || null;
  const lines = [`${command}: ${result.ok === false ? 'blocked' : 'ready'}`];
  if (result.operation) lines.push(`executed: ${result.operation}`);
  if (result.verdict) {
    lines.push(`verdict: ${result.verdict}`);
    // Name the skip reason. An unattended supervisor has to tell a retryable
    // git-busy landing apart from a commit-gate refusal that needs a human.
    lines.push(`committed: ${result.committed ? 'yes' :
      `no (${result.commit?.skipped || 'unknown'})`}`);
  }
  if (result.lint?.status) lines.push(`lint: ${result.lint.status}`);
  if (next) {
    lines.push(`next [${next.code || 'unstructured'}]: ${next.value || '(none)'}`);
  }
  return `${lines.join('\n')}\n`;
}

function writeFacadeResult(command, args, result) {
  process.stdout.write(args.json === true ?
    `${JSON.stringify(result, null, 2)}\n` : renderFacadeResult(command, result));
}

function cmdStart(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('start: --id <questId> is required');
  const doctor = buildDoctorReport(root);
  if (!fs.existsSync(questFilePath(root, id))) {
    if (typeof args.statement !== 'string') {
      throw new Error(
        'start: unknown Quest; pass --statement "<sealed result>" to create it',
      );
    }
    cmdNew(root, {...args, id, quiet: true});
  }
  writeFacadeResult('start', args, startQuestWorkflow(root, {...args, id, doctor}));
}

function cmdContinue(root, args) {
  const result = continueQuestWorkflow(root, args);
  if (result.executed) refreshFrontierBoard(root);
  writeFacadeResult('continue', args, result);
}

function cmdLand(root, args) {
  const result = landQuestWorkflow(root, args);
  refreshFrontierBoard(root);
  writeFacadeResult('land', args, result);
}

// Discharge a slice of a standing candidate rejection with fresh approved
// coverage (current candidate or --from-quest <successorId>), so split scope
// stays dischargeable instead of forcing one ever-growing superset candidate.
function cmdDecomposeRejection(root, args) {
  const result = recordRejectionDecomposition(root, args);
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}

// Draft-time retread check (and again on each supervised pin): warn when the
// statement cites files/CL-ids touched by a recent revert, and surface the
// lineage's recorded dead levers. Purely advisory; must never fail the command.
function emitRetreadWarnings(root, quest) {
  let lines;
  try {
    lines = retreadCheckLines(root, quest);
  } catch (err) {
    process.stderr.write(`retread check skipped: ${err.message}\n`);
    return;
  }
  if (lines.length === 0) return;
  process.stdout.write(`${lines.join('\n')}\n`);
}

function buildRunOptions(root, id, args) {
  const unsupported = ['commit-every', 'stall-window', 'no-commit']
    .filter((name) => args[name] !== undefined);
  if (unsupported.length > 0) {
    throw new Error(
      `run: unsupported option(s): ${unsupported.map((name) => `--${name}`).join(', ')}`,
    );
  }
  const executor = buildExecutor(root, id, args);
  const options = {executor};
  if (args.max !== undefined) options.maxCycles = Number(args.max);
  return options;
}

function writeRunOutcome(root, id, result) {
  const problems = result.problems?.length ?
    `problems:\n${result.problems.map((problem) => `- ${problem}`).join('\n')}\n` :
    '';
  const disposition = result.disposition ?
    `disposition: ${result.disposition}\n` : '';
  const next = result.nextCommand ? `next: ${result.nextCommand}\n` : '';
  const nextAction = result.nextAction ?
    `next action [${result.nextAction.type}]: ${result.nextAction.value || '(none)'}\n` : '';
  const supervisor = result.supervisor ?
    `supervisor: ${result.supervisor.stop} ` +
    `(restarts: ${result.supervisor.restarts}` +
    (result.supervisor.innerOutcome ?
      `, inner: ${result.supervisor.innerOutcome}` : '') + ')\n' : '';
  process.stdout.write(
    `terminal: ${result.outcome}\nevidence: ${result.evidence || '(none)'}\n` +
    supervisor +
    disposition +
    problems +
    next +
    nextAction +
    commitLine(result.commit) +
    `report: on demand via node scripts/solve.js report --id ${id}\n`);
  refreshFrontierBoard(root);
}

function cmdRun(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('run: --id <questId> is required');
  const quest = loadQuest(root, id);
  const options = buildRunOptions(root, id, args);
  if (args['keep-alive']) {
    if (args['max-restarts'] !== undefined) {
      options.maxRestarts = Number(args['max-restarts']);
    }
    options.onRestart = ({restarts, innerOutcome}) => process.stderr.write(
      `supervisor: restart ${restarts} after ${innerOutcome}\n`);
    writeRunOutcome(root, id, runSupervised(root, quest, options));
    return;
  }
  writeRunOutcome(root, id, runLoop(root, quest, options));
}

function buildExecutor(root, id, args) {
  const kind = args.executor || 'dry';
  if (kind === 'dry') {
    process.stderr.write(DRY_EXECUTOR_NOTICE);
    return makeDryExecutor({
      changeDir: path.join(root, SOLVE_DATA_DIR, 'changes', id),
      step: Number(args.step) || 1,
    });
  }
  if (kind === 'agent') {
    // Real edits: gated behind an explicit flag so it is never the default.
    if (!args.yes) {
      throw new Error(
        'run --executor agent performs real edits; pass --yes to confirm');
    }
    return makeAgentExecutor(root, {repoRoot: root});
  }
  throw new Error(`run: unknown executor "${kind}" (use dry|agent)`);
}

function questAdvisories(root, quest, log) {
  const health = analyzeQuestHealth(root, quest);
  const questLog = log || readLog(root, quest.id);
  const advisories = buildAdvisories(quest, health, questLog);
  const sealFreshness = buildSealFreshnessAdvisory(quest, questLog, {root});
  if (sealFreshness) advisories.push(sealFreshness);
  return advisories;
}

// Print the workflow advisories (reflection-due / override-available) for a quest, so a
// supervised driver sees the same nudges the autonomous loop would act on. No-op when none.
function emitAdvisories(root, quest) {
  const advisories = questAdvisories(root, quest);
  if (advisories.length === 0) return;
  process.stdout.write(`${renderAdvisoryLines(advisories).join('\n')}\n`);
}

function cmdStatus(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('status: --id <questId> is required');
  const quest = loadQuest(root, id);
  const log = readLog(root, id);
  const state = projectState(quest, log);
  const status = {
    ...state,
    currentBlocker: buildCurrentBlocker({quest, log, state}),
    scopePressure: analyzeScopePressure(root, quest, log),
    advisories: questAdvisories(root, quest, log),
  };
  process.stdout.write(`${JSON.stringify(status, null, 2)}\n`);
}

function cmdReport(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('report: --id <questId> is required');
  const {file, md} = writeReport(root, id);
  const unrecorded = detectUnrecordedEvidence(root, id);
  const warning = unrecorded ?
    `\nWARNING: fresh probe evidence is not recorded. Run:\n  ${unrecorded.command}\n` :
    '';
  const advisories = questAdvisories(root, loadQuest(root, id));
  const advisoryText = advisories.length ?
    `\n${renderAdvisoryLines(advisories).join('\n')}\n` :
    '';
  process.stdout.write(`${md}${warning}${advisoryText}\n(written to ${file})\n`);
  refreshFrontierBoard(root);
}

function cmdProbe(root, args) {
  const name = args.probe;
  if (!name) throw new Error('probe: --probe <name> is required');
  const probeArgs = {...args};
  delete probeArgs._;
  delete probeArgs.probe;
  const result = evaluate({probe: name, args: probeArgs}, {root});
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}

function optionalStringArgument(args, name) {
  return typeof args[name] === 'string' ? args[name] : null;
}

function cmdFinding(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('finding: --id <questId> is required');
  if (!args.frontier) throw new Error('finding: --frontier <frontierId> is required');
  if (typeof args.claim !== 'string') {
    throw new Error('finding: --claim "<what was learned>" is required');
  }
  const quest = loadQuest(root, id);
  const regressionLabels = Array.isArray(args['regression-label']) ?
    args['regression-label'] :
    (typeof args['regression-label'] === 'string' ?
      [args['regression-label']] :
      []);
  const regressionClassification = typeof args['regression-resolution'] === 'string' ?
    {
      resolution: args['regression-resolution'],
      labels: regressionLabels,
      regressionEventIndex: args['regression-event'] !== undefined ?
        Number(args['regression-event']) :
        null,
      evidenceFingerprint: typeof args['regression-fingerprint'] === 'string' ?
        args['regression-fingerprint'] :
        null,
    } :
    null;
  const scopePressureClassification =
    typeof args['scope-pressure-resolution'] === 'string' ?
      {
        resolution: args['scope-pressure-resolution'],
        changeRef: typeof args['scope-pressure-change-ref'] === 'string' ?
          args['scope-pressure-change-ref'] :
          null,
      } :
      null;
  const kind = optionalStringArgument(args, 'kind');
  const evidence = optionalStringArgument(args, 'evidence');
  // A rejection must carry its category-complete finding list durably; a
  // pointer-only claim satisfies every downstream consumer mechanically while
  // carrying zero content (measured 2026-07-27).
  const rejectionFindings = kind === VERIFIER_REJECTION_FINDING_KIND ?
    parseRejectionFindings(args.finding) : [];
  if (kind === VERIFIER_REJECTION_FINDING_KIND) {
    if (rejectionFindings.length === 0) {
      throw new Error(
        `finding: verifier-rejection requires ${REJECTION_FINDING_USAGE}`);
    }
    const barProblem = rejectionFindingBarProblem(
      quest, readLog(root, id), rejectionFindings);
    if (barProblem) throw new Error(`finding: ${barProblem}`);
  }
  const verificationScope = optionalStringArgument(args, 'verification-scope');
  const verificationFingerprint =
    optionalStringArgument(args, 'verification-fingerprint');
  let verificationReceipt = null;
  let verificationSchemaVersion = null;
  if (kind && verificationScope) {
    const verificationProjection = verificationState(
      root, quest, readLog(root, id));
    if (verificationScope === VERIFICATION_SCOPE.CANDIDATE) {
      verificationReceipt = verificationProjection.candidate;
      verificationSchemaVersion = VERIFICATION_CONTRACT_VERSION;
      if (!verificationReceipt?.ok ||
        verificationReceipt.fingerprint !== verificationFingerprint) {
        throw new Error('candidate verification fingerprint does not match current bytes');
      }
    } else if ([VERIFICATION_SCOPE.AGGREGATE, VERIFICATION_SCOPE.BOTH]
      .includes(verificationScope) &&
      verificationProjection.attempts.some((attempt) => attempt.candidateContract)) {
      const candidateAttempts = verificationProjection.attempts.filter(
        (attempt) => attempt.candidateContract);
      verificationReceipt = {
        ...verificationProjection.aggregate,
        sourcePaths: verificationProjection.aggregate.paths,
        firstAttemptIndex: candidateAttempts[0].index,
        lastAttemptIndex: candidateAttempts[candidateAttempts.length - 1].index,
      };
      verificationSchemaVersion = VERIFICATION_CONTRACT_VERSION;
      if (!verificationReceipt.ok ||
        verificationReceipt.fingerprint !== verificationFingerprint) {
        throw new Error('aggregate verification fingerprint does not match current bytes');
      }
    }
  }
  const verification = buildVerificationFinding({
    kind,
    evidence,
    verificationScope,
    verificationFingerprint,
    verificationReceipt,
    verificationSchemaVersion,
    rejectionFindings,
  });
  const stamped = appendFinding(root, id, {
    frontier: args.frontier,
    claim: args.claim,
    kind,
    evidence,
    rulesOut: typeof args.rulesOut === 'string' ? args.rulesOut : null,
    regressionClassification,
    scopePressureClassification,
    verification,
  });
  process.stdout.write(`recorded finding for ${args.frontier} @ ${stamped.ts}\n`);
}

function cmdLint(root, args) {
  const id = args.id || args._[0];
  if (!id && args.all !== true) {
    throw new Error(LOCAL_STR_OWNED_008);
  }
  const result = lintQuestCorpus(root, {id, all: args.all === true});
  process.stdout.write(args.json === true ?
    `${JSON.stringify(result, null, 2)}\n` : renderQuestLint(result));
  if (result.status !== LOCAL_STR_OWNED_009) process.exitCode = 1;
}

function cmdCheckpoint(root, args) {
  process.stdout.write(runCheckpointCommand(root, args));
}

const PROMOTE_DOMAINS = Object.freeze(['architecture', 'testing', 'governance', 'style']);
const NORMATIVE_KEYWORD = /\b(MUST NOT|MUST|SHOULD NOT|SHOULD|SHALL NOT|SHALL|NEVER|MAY)\b/;
const PACK_CONFIG_REL = 'docs/steering/llm-pack.config.json';
const FINDINGS_REL = 'docs/steering/findings';

function slugify(text) {
  return String(text).toLowerCase().replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '').slice(0, 48) || 'finding';
}

function isoDate() {
  return new Date().toISOString().slice(0, 10);
}

// Append a {file, domain, priority} entry to the pack config so the generator picks
// up the new findings file with the right domain. The generator keys domain off the
// config entry (not file front-matter), so this is the only place domain is carried.
function appendPackSource(root, relFile, domain) {
  const configPath = path.join(root, PACK_CONFIG_REL);
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  config.sources = config.sources || [];
  if (config.sources.some((s) => s.file === relFile)) return false;
  config.sources.push({file: relFile, domain, priority: 100});
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`);
  return true;
}

// Promote a recorded Quest finding into a durable source-steering file. Findings
// have no key — they are addressed by (quest, frontier) and disambiguated by
// --match (claim substring) or --ts when a frontier carries several. The body is
// the finding's claim; it must read as a normative sentence to become a rule.
function cmdPromoteFinding(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('promote-finding: --id <questId> is required');
  if (!args.frontier) throw new Error('promote-finding: --frontier <frontierId> is required');
  const domain = typeof args.domain === 'string' ? args.domain : null;
  if (!domain || !PROMOTE_DOMAINS.includes(domain)) {
    throw new Error(`promote-finding: --domain <${PROMOTE_DOMAINS.join('|')}> is required ` +
      '(the pack generator cannot infer domain from the file)');
  }
  loadQuest(root, id);
  let findings = readFindings(root, id, args.frontier);
  if (findings.length === 0) {
    throw new Error(`promote-finding: no findings recorded for ${id} / ${args.frontier}`);
  }
  if (typeof args.match === 'string') {
    findings = findings.filter((f) => (f.claim || '').includes(args.match));
  }
  if (typeof args.ts === 'string') {
    findings = findings.filter((f) => f.ts === args.ts);
  }
  if (findings.length === 0) {
    throw new Error('promote-finding: no finding matched --match/--ts');
  }
  if (findings.length > 1) {
    throw new Error(`promote-finding: ${findings.length} findings match; narrow with ` +
      '--match "<claim substring>" or --ts <iso>');
  }
  const finding = findings[0];
  const claim = finding.claim || '';
  const slug = typeof args.slug === 'string' ? slugify(args.slug) : slugify(claim);
  const baseName = `${isoDate()}-${id}-${slug}.md`;
  const relFile = `findings/${baseName}`; // relative to docs/steering (sourceDir)
  const absFile = path.join(root, FINDINGS_REL, baseName);
  if (fs.existsSync(absFile) && !args.force) {
    throw new Error(`promote-finding: ${absFile} already exists (use --force)`);
  }
  const body = `---\nsource: quest:${id}#${args.frontier}\n---\n\n${claim}\n`;
  fs.mkdirSync(path.dirname(absFile), {recursive: true});
  fs.writeFileSync(absFile, body);
  const added = appendPackSource(root, relFile, domain);
  process.stdout.write(`promoted finding -> ${absFile}\n`);
  process.stdout.write(added ?
    `added sources[] entry {file:"${relFile}", domain:"${domain}", priority:100}\n` :
    `(sources[] already had ${relFile})\n`);
  if (!NORMATIVE_KEYWORD.test(claim)) {
    process.stdout.write(
      'WARNING: claim has no normative keyword (MUST/SHOULD/NEVER/...). The pack ' +
      'generator will classify it as `info` and it will NOT become a rule. Edit the ' +
      `body of ${relFile} into a normative sentence before regenerating.\n`);
  }
  process.stdout.write('next: npm run steering:llm:pack && npm run steering:check\n');
}

// Friendly aliases for the overridable guard codes so a driver can write `--guard theory`
// or `--guard scope` instead of the internal continuation code.
const OVERRIDE_GUARD_ALIASES = Object.freeze({
  'theory': CONTINUATION_BLOCKED_THEORY,
  'blocked-theory': CONTINUATION_BLOCKED_THEORY,
  'scope': CONTINUATION_BLOCKED_SCOPE,
  'blocked-scope': CONTINUATION_BLOCKED_SCOPE,
});

const OVERRIDE_REAUTHORIZED_LINE =
  '(re-authorizes an already-covered scope — no lifetime budget spent)\n';
const OVERRIDE_CHARGED_LINE =
  '(authorizes one bypass of the next matching guard; reset by honest progress)\n';

// The scope this override authorizes, read from the change artifacts already on
// record — never from the operator's --reason. A later override whose scope is
// covered by this one is re-authorizing unchanged work (a voided receipt, a
// verifier-required repair of the same candidate) rather than growing scope, and
// must not spend lifetime budget. Advisory-derived: if the analysis cannot run we
// record no signature, which charges the override exactly as before.
function authorizedScopeSignature(root, quest) {
  try {
    return analyzeScopePressure(root, quest, readLog(root, quest.id),
      {ignoreBaselines: true}).changedPaths || null;
  } catch {
    return null;
  }
}

function cmdOverride(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('override: --id <questId> is required');
  if (!args.frontier) throw new Error('override: --frontier <frontierId> is required');
  const selector = typeof args.guard === 'string' ? args.guard :
    (typeof args.code === 'string' ? args.code : null);
  if (!selector) {
    throw new Error('override: --guard <theory|scope> (or --code <continuation-code>) ' +
      'is required');
  }
  const code = OVERRIDE_GUARD_ALIASES[selector] || selector;
  if (!continuationOverridable({status: code, code})) {
    throw new Error(`override: guard "${selector}" is not overridable. Only the heuristic ` +
      'theory and scope guards accept an override; honesty/integrity invariants ' +
      '(regression, unrecorded-evidence, metric-projection, measurement) do not.');
  }
  if (typeof args.reason !== 'string' || !args.reason.trim()) {
    throw new Error('override: --reason "<falsifiable justification>" is required');
  }
  const quest = loadQuest(root, id);
  const stamped = appendGuardOverride(root, id, {
    frontier: args.frontier,
    code,
    problem: typeof args.problem === 'string' ? args.problem : null,
    reason: args.reason,
    scopeSignature: authorizedScopeSignature(root, quest),
  });
  process.stdout.write(
    `recorded override of ${code} for ${args.frontier} @ ${stamped.ts}\n` +
    (stamped.scopeReauthorization ?
      OVERRIDE_REAUTHORIZED_LINE : OVERRIDE_CHARGED_LINE));
}

function cmdReflect(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('reflect: --id <questId> is required');
  if (typeof args.note !== 'string' || !args.note.trim()) {
    throw new Error('reflect: --note "<free-form reframing>" is required');
  }
  loadQuest(root, id);
  const altitude = args.altitude === true;
  const stamped = appendReflection(root, id, {
    frontier: typeof args.frontier === 'string' ? args.frontier : null,
    trigger: typeof args.trigger === 'string' ? args.trigger :
      (altitude ? 'on-demand' : 'manual'),
    kind: altitude ? 'altitude' : 'micro',
    note: args.note,
  });
  process.stdout.write(
    `recorded ${altitude ? 'altitude ' : ''}reflection @ ${stamped.ts}\n`);
}
function writeStepTerminal(root, quest, result) {
  if (result.terminal === 'theory-required' || result.terminal === 'blocked') {
    const header = result.terminal === 'theory-required' ?
      `THEORY REQUIRED — ${result.frontier} rung ${result.rungIndex}` :
      `BLOCKED (${result.disposition || 'recoverable'}) — ${result.frontier} ` +
      `rung ${result.rungIndex}`;
    const next = result.nextCommand ? `\nnext: ${result.nextCommand}` : '';
    process.stdout.write(
      `${header}\n` +
      `${(result.problems || []).map((problem) => `- ${problem}`).join('\n')}` +
      `${next}\n`);
    emitAdvisories(root, quest);
    refreshFrontierBoard(root);
    return true;
  }
  if (result.terminal === 'solved') {
    process.stdout.write(`SOLVED — evidence: ${result.evidence || '(none)'}\n`);
    refreshFrontierBoard(root);
    return true;
  }
  if (result.terminal === 'exhausted') {
    process.stdout.write('EXHAUSTED — no open frontier; human decision needed\n');
    refreshFrontierBoard(root);
    return true;
  }
  return false;
}

function validateStepCommitArguments(args) {
  if (args.changeRef && !args.commit) {
    throw new Error('step commit requires --commit with --changeRef');
  }
  if (args[AUTO_DIFF_ARGUMENT] && !args.commit) {
    throw new Error(AUTO_DIFF_REQUIRES_COMMIT);
  }
  if (args[AUTO_DIFF_ARGUMENT] && args.changeRef) {
    process.stderr.write(AUTO_DIFF_IGNORED_NOTICE);
  }
  if (args.commit && !args.changeRef && !args[AUTO_DIFF_ARGUMENT]) {
    throw new Error(STEP_CHANGE_REF_REQUIRED);
  }
}

function cmdStep(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('step: --id <questId> is required');
  const quest = loadQuest(root, id);
  if (args.abort) {
    process.stdout.write(stepAbort(root, id) ?
      'pending step aborted\n' :
      'no pending step\n');
    return;
  }
  validateStepCommitArguments(args);
  const r = runStep(root, quest, {
    changeRef: typeof args.changeRef === 'string' ? args.changeRef : undefined,
    autoDiff: Boolean(args[AUTO_DIFF_ARGUMENT]),
    summary: typeof args.summary === 'string' ? args.summary : undefined,
    force: Boolean(args.force),
    ...theoryCommitArgs(args),
  });
  if (writeStepTerminal(root, quest, r)) return;
  if (!args.commit) {
    process.stdout.write(
      `pinned ${r.frontier}: metric ${r.before.metric}\n` +
      `pending: ${r.pendingFile}\n` +
      `next: node scripts/solve.js step --id ${id} --commit ` +
      STEP_NEXT_ARGUMENTS,
    );
    emitRetreadWarnings(root, quest);
    emitAdvisories(root, quest);
    return;
  }
  const moved = r.progressed ? 'PROGRESS' : 'flat';
  const viol = r.violations.length ? ` violations: ${r.violations.join('; ')}` : '';
  const autoDiffLine = args[AUTO_DIFF_ARGUMENT] && r.changeRef ?
    `changeRef: ${r.changeRef}\n` : '';
  const templateLines = (r.verificationTemplates || [])
    .map((t) => `suggested verification template: ${t.template}\n`).join('');
  const witnessLine = r.engagementWitness && !r.engagementWitness.satisfied ?
    `${r.engagementWitness.message}\n` : '';
  process.stdout.write(
    `recorded attempt on ${r.frontier}: metric ${r.before} -> ${r.after} ` +
    `(${moved})${r.done ? ' DONE' : ''}${viol}\n${autoDiffLine}${templateLines}` +
    witnessLine + commitLine(r.commit));
  emitAdvisories(root, quest);
  refreshFrontierBoard(root);
}

// "What do I do next?" — thin renderer over the existing read-models (pending step,
// gate stops, current blocker, advisories). Derives nothing new; see solve/next.js.
function cmdNext(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error(NEXT_ID_REQUIRED);
  process.stdout.write(runNextCommand(root, id, {json: args.json === true}));
}

function cmdDoctor(root, args) {
  const report = buildDoctorReport(root);
  process.stdout.write(args.json === true ?
    `${JSON.stringify(report, null, 2)}\n` : renderDoctor(report));
}

// Keep the generated frontier board (solve/FRONTIER.generated.md) fresh at the
// quest lifecycle points that change board state, so boot orientation never
// reads a stale board. Board regeneration must never fail the lifecycle
// command that triggered it.
function refreshFrontierBoard(root) {
  try {
    writeFrontier(root, runFrontierCommand(root));
  } catch (err) {
    process.stderr.write(`frontier board refresh skipped: ${err.message}\n`);
  }
}

// One-line human summary of the auto-commit outcome, printed after a step.
// The Solver only ever commits — it never pushes (see autoCommitQuest).
function commitLine(commit) {
  if (!commit) return '';
  if (commit.committed) {
    return `committed ${commit.paths.length} path(s), not pushed\n`;
  }
  return `no auto-commit (${commit.skipped})\n`;
}

function cmdTheory(root, args) {
  process.stdout.write(`${runTheoryCommand(root, args)}\n`);
}

function cmdHealth(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('health: --id <questId> is required');
  const quest = loadQuest(root, id);
  const health = analyzeQuestHealth(root, quest);
  const advisories = questAdvisories(root, quest, readLog(root, id));
  if (args.json) {
    process.stdout.write(`${JSON.stringify({...health, advisories}, null, 2)}\n`);
  } else {
    process.stdout.write(renderHealth(health));
    if (advisories.length) {
      process.stdout.write(`\n${renderAdvisoryLines(advisories).join('\n')}\n`);
    }
  }
}

function cmdStepPending(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('step-pending: --id <questId> is required');
  process.stdout.write(`${JSON.stringify(stepPending(root, id), null, 2)}\n`);
}

function cmdIngestEvidence(root, args) {
  const id = args.id || args._[0];
  if (!id) throw new Error('ingest-evidence: --id <questId> is required');
  const frontier = args.frontier;
  if (!frontier) throw new Error('ingest-evidence: --frontier <frontierId> is required');
  const evidence = args.evidence;
  if (!evidence) throw new Error('ingest-evidence: --evidence <evidencePath> is required');

  const stamped = ingestEvidence(root, {
    questId: id,
    frontierId: frontier,
    evidencePath: evidence,
    probeScope: args.probe === 'doneWhen' ? 'doneWhen' : 'frontier',
  });
  process.stdout.write(`Ingested evidence: ${stamped.evidence} for ${frontier}\n`);
}

function cmdAttempt(root, args) {
  const result = runAttemptCommand(root, {
    ...args,
    ...theoryCommitArgs(args),
  });
  if (result && result.blocked) {
    const header = result.terminal === 'theory-required' ?
      `THEORY REQUIRED — ${result.frontier} rung ${result.rungIndex}` :
      `BLOCKED (${result.disposition || 'recoverable'}) — ` +
      `${result.frontier} rung ${result.rungIndex}`;
    const next = result.nextCommand ? `\nnext: ${result.nextCommand}` : '';
    process.stdout.write(
      `${header}\n` +
      `${(result.problems || []).map((problem) => `- ${problem}`).join('\n')}` +
      `${next}\n`);
    return;
  }
  process.stdout.write('Harness execution attempt complete and recorded.\n');
}

function cmdAudit(root, args) {
  const output = runAuditCommand(root, args);
  process.stdout.write(output);
}

function cmdUpgrade(root, args) {
  process.stdout.write(runUpgradeCommand(root, args));
}

function cmdReopen(root, args) {
  process.stdout.write(runReopenCommand(root, args));
}

function cmdPark(root, args) {
  process.stdout.write(runParkCommand(root, args));
}

// Portfolio is a cross-quest governance view and deliberately takes no --id.
function cmdPortfolio(root) {
  process.stdout.write(runPortfolioCommand(root));
}

// Commit-level meta-to-product ratio for the retrospective cadence; like
// portfolio it is cross-cutting and takes no --id.
function cmdMetaRatio(root, args) {
  process.stdout.write(`${runMetaRatioCommand(root, {days: args.days})}\n`);
}

// Ranks recorded workflow friction (violations, charged guard overrides, parks) so a
// retrospective starts from what actually fired rather than from what was remembered.
// Cross-cutting like meta-ratio and portfolio; takes no --id.
function cmdMetaFriction(root, args) {
  process.stdout.write(`${runMetaFrictionCommand(root, {days: args.days})}\n`);
}

function cmdCost(root, args) {
  process.stdout.write(`${runCostCommand(root, {days: args.days})}\n`);
}

function cmdAmend(root, args) {
  process.stdout.write(`${runAmendCommand(root, args)}\n`);
}

function cmdInheritCandidate(root, args) {
  process.stdout.write(`${runInheritCandidateCommand(root, args)}\n`);
}

function cmdCorrectAttemptBase(root, args) {
  process.stdout.write(`${runAttemptBaseCorrectionCommand(root, args)}\n`);
}

// Frontier fuses the closure-ledger active records with the open quests into one
// boot-orientation screen; like portfolio it is cross-cutting and takes no --id.
// --write also persists solve/FRONTIER.generated.md (a regenerable board file).
function cmdFrontier(root, args) {
  const md = runFrontierCommand(root);
  if (args.write) {
    const file = writeFrontier(root, md);
    process.stdout.write(`wrote ${file}\n`);
  }
  process.stdout.write(md);
}

// trace joins the otherwise-disconnected planning layers via each quest's optional
// `links` block. Pick exactly one selector:
//   --row <id>   quests whose links.roadmapRow === id
//   --cl <CL-#>  quests whose links.closesCL includes the record
//   --spec <ref> quests whose links.specRef starts with ref
//   --quest <id> reverse view: this quest's links + its child quests (parentQuest)
// It asserts nothing the sealed quest files do not already contain.
function traceRow(quest, portfolioById) {
  const row = portfolioById.get(quest.id);
  const outcome = row ? row.outcome : 'unknown';
  const klass = row ? row.class : '?';
  return `| ${quest.id} | ${klass} | ${outcome} |`;
}

function cmdTrace(root, args) {
  const selectors = ['row', 'cl', 'spec', 'quest'].filter((k) => args[k] !== undefined);
  if (selectors.length !== 1) {
    throw new Error('trace: pass exactly one of --row <id> | --cl <CL-#> | ' +
      '--spec <ref> | --quest <id>');
  }
  const quests = loadAllQuests(root);
  const portfolioById = new Map(buildPortfolio(root).rows.map((r) => [r.id, r]));
  const out = [];
  if (args.quest !== undefined) {
    const id = String(args.quest);
    const self = quests.find((q) => q.id === id);
    if (!self) throw new Error(`trace: no quest "${id}"`);
    const links = self.links || {};
    out.push(`# trace ${id}`, '', '## Links');
    out.push(`- roadmap row: ${links.roadmapRow || '—'}`);
    out.push(`- spec: ${links.specRef || '—'}`);
    out.push(`- closes: ${(links.closesCL || []).join(', ') || '—'}`);
    out.push(`- parent quest: ${links.parentQuest || '—'}`);
    const children = quests.filter((q) => (q.links || {}).parentQuest === id);
    out.push('', `## Child quests — ${children.length}`);
    if (children.length === 0) {
      out.push('_(none)_');
    } else {
      out.push('| id | class | outcome |', '| --- | --- | --- |');
      for (const c of children) out.push(traceRow(c, portfolioById));
    }
    process.stdout.write(`${out.join('\n')}\n`);
    return;
  }
  let match;
  let title;
  if (args.row !== undefined) {
    const v = String(args.row);
    title = `quests for roadmap row ${v}`;
    match = (q) => (q.links || {}).roadmapRow === v;
  } else if (args.cl !== undefined) {
    const v = String(args.cl);
    title = `quests closing ${v}`;
    match = (q) => Array.isArray((q.links || {}).closesCL) && q.links.closesCL.includes(v);
  } else {
    const v = String(args.spec);
    title = `quests for spec ${v}`;
    match = (q) => typeof (q.links || {}).specRef === 'string' && q.links.specRef.startsWith(v);
  }
  const hits = quests.filter(match);
  out.push(`# trace — ${title}`, '', `${hits.length} match(es)`, '');
  if (hits.length > 0) {
    out.push('| id | class | outcome |', '| --- | --- | --- |');
    for (const q of hits) out.push(traceRow(q, portfolioById));
  }
  process.stdout.write(`${out.join('\n')}\n`);
}

function cmdOverview(root, args) {
  if (args.write) {
    const file = writeOverview(root);
    process.stdout.write(`wrote ${path.relative(root, file)}\n`);
    return;
  }
  process.stdout.write(runOverviewCommand(root));
}

function cmdHandoff(root, args) {
  process.stdout.write(runHandoffCommand(root, args));
}

// Tier-2 live-evidence verification of architecture invariants (standing dual of
// doneWhen). `--evaluate` runs each invariant's predicate and records the verdict;
// otherwise status is derived from the event log. Always active (unconditional).
function changedFilesFromArgs(root, args) {
  if (typeof args.changed === 'string') {
    return args.changed.split(',').map((file) => file.trim()).filter(Boolean);
  }
  if (typeof args.since === 'string') {
    const out = spawnSync('git', ['diff', '--name-only', args.since], {cwd: root, encoding: 'utf8'});
    return (out.stdout || '').split('\n').map((file) => file.trim()).filter(Boolean);
  }
  return null;
}

function cmdInvariants(root, args) {
  // --export: write a durable, cross-session status board (a projection, not a store).
  if (args.export) {
    const board = renderInvariantBoard(root, {});
    const out = typeof args.out === 'string' ?
      args.out : path.join(root, 'solve', 'invariant-status.generated.md');
    fs.mkdirSync(path.dirname(out), {recursive: true});
    fs.writeFileSync(out, board);
    process.stdout.write(`wrote ${out}\n`);
    return;
  }
  // --score: local EvoClaw-style coverage/coherence over the repro-backed surface.
  if (args.score) {
    const result = scoreInvariants(root, {evaluate: Boolean(args.evaluate)});
    if (args.json) {
      process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
      return;
    }
    const pct = (value) => (value === null ? 'n/a' : `${Math.round(value * 100)}%`);
    process.stdout.write(
      'standing-invariant score (local, EvoClaw-style — not the external benchmark):\n' +
      `  coverage:  ${result.guardedReproBackedCLs}/${result.reproBackedCLs} repro-backed CLs guarded (${pct(result.coverage)})\n` +
      `  coherence: ${result.held}/${result.liveInvariants} live invariants HELD (${pct(result.coherence)}) ` +
      `[${result.breached} breached, ${result.unguarded} unguarded]\n` +
      `  worklist (unguarded repro-backed CLs): ${result.unguardedReproBackedCLs.join(LOCAL_STR_OWNED_010) || '(none)'}\n`);
    return;
  }
  // on-touched-owner trigger: re-verify invariants whose paths intersect changed files.
  const changedFiles = changedFilesFromArgs(root, args);
  if (changedFiles) {
    const fired = triggerOnTouchedOwner(root, {changedFiles});
    if (args.json) {
      process.stdout.write(`${JSON.stringify(fired, null, 2)}\n`);
      return;
    }
    const lines = fired.transitions.map((t) => `${t.from} -> ${t.to}  ${t.id}`);
    process.stdout.write(
      `on-touched-owner re-verification (${fired.transitions.length} invariant(s)):\n` +
      `${lines.join(LINE_SEPARATOR) || '(none matched the changed files)'}\n`);
    return;
  }
  const out = runInvariantsCommand(root, args);
  if (args.json) {
    process.stdout.write(`${JSON.stringify(out, null, 2)}\n`);
    return;
  }
  if (out.invariants.length === 0) {
    process.stdout.write('no invariants carry a liveEvidence (Tier-2) block.\n');
    return;
  }
  const lines = out.invariants.map((row) => {
    const tags = `[${row.cost || '?'}, ${row.trigger || '?'}]`;
    const ref = row.evidenceRef ? `  <- ${row.evidenceRef}` : '';
    const tally = row.evaluations ?
      `  (${row.evaluations} eval${row.evaluations === 1 ? '' : 's'}, last ${row.verdict})` : '';
    return `${row.status.padEnd(9)} ${row.id}  ${tags}${ref}${tally}`;
  });
  const header = out.evaluated ?
    'standing invariants (evaluated now):' :
    'standing invariants (derived from event log):';
  process.stdout.write(`${header}\n${lines.join('\n')}\n`);
}

const COMMANDS = {
  'start': cmdStart,
  'continue': cmdContinue,
  'land': cmdLand,
  'decompose-rejection': cmdDecomposeRejection,
  'new': cmdNew,
  'run': cmdRun,
  'status': cmdStatus,
  'report': cmdReport,
  'portfolio': cmdPortfolio,
  'meta-ratio': cmdMetaRatio,
  'meta-friction': cmdMetaFriction,
  'cost': cmdCost,
  'frontier': cmdFrontier,
  'overview': cmdOverview,
  'trace': cmdTrace,
  'handoff': cmdHandoff,
  'checkpoint': cmdCheckpoint,
  'invariants': cmdInvariants,
  'probe': cmdProbe,
  'finding': cmdFinding,
  'promote-finding': cmdPromoteFinding,
  'override': cmdOverride,
  'reflect': cmdReflect,
  'step': cmdStep,
  'step-pending': cmdStepPending,
  'next': cmdNext,
  'doctor': cmdDoctor,
  'lint': cmdLint,
  'theory': cmdTheory,
  'health': cmdHealth,
  'ingest-evidence': cmdIngestEvidence,
  'attempt': cmdAttempt,
  'audit': cmdAudit,
  'upgrade': cmdUpgrade,
  'reopen': cmdReopen,
  'park': cmdPark,
  'amend': cmdAmend,
  'inherit-candidate': cmdInheritCandidate,
  'correct-attempt-base': cmdCorrectAttemptBase,
};

function main() {
  const [, , command, ...rest] = process.argv;
  const handler = COMMANDS[command];
  if (!handler) {
    process.stderr.write(
      `usage: solve <${Object.keys(COMMANDS).join(COMMAND_SEPARATOR)}> ` +
      USAGE_ARGUMENTS);
    process.exit(command ? 1 : 0);
    return;
  }
  let args;
  if (command === 'attempt') {
    const dashDashIndex = process.argv.indexOf('--');
    if (dashDashIndex !== -1) {
      const commandArgs = process.argv.slice(3, dashDashIndex);
      const harnessCmd = process.argv.slice(dashDashIndex + 1);
      args = parseArgs(commandArgs);
      args._ = harnessCmd;
    } else {
      args = parseArgs(rest);
    }
  } else {
    args = parseArgs(rest);
  }
  const root = args.root || process.cwd();
  try {
    handler(root, args);
  } catch (error) {
    process.stderr.write(`error: ${error.message}\n`);
    process.exit(1);
  }
}

main();
