{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "system-endpoint-sync-controller.fullname" . }}
  labels:
    {{- include "system-endpoint-sync-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "system-endpoint-sync-controller.fullname" . }}
  labels:
    {{- include "system-endpoint-sync-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "system-endpoint-sync-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "system-endpoint-sync-controller.fullname" . }}
{{- end }}
