// Auto-diff change artifacts — the single owner of working-tree snapshotting.
//
// Extracted from step.js so every attempt-recording verb (supervised step,
// component attempt, replacement re-attempt) builds its sealed artifact
// through one code path instead of hand-rolled git incantations (measured
// 2026-09-01: a replacement attempt hand-built with internal APIs omitted a
// regenerated dependency and cost a full land/override cycle to discover).

import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

import {
  changedPathsFromDiffContent,
  expectedChangeDir,
  isForeignQuestBookkeeping,
} from './change-artifact.js';
import {
  writeContentAddressedChangeArtifact,
} from './content-addressed-change-artifact.js';
import {registeredGeneratedOutputPaths} from './generated-dependencies.js';
import {questContractExcludesCollateral} from './verification.js';

const AUTO_DIFF_ARTIFACT_PREFIX = 'attempt-';
const AUTO_DIFF_ARTIFACT_EXTENSION = '.diff';
const AUTO_DIFF_ARTIFACT_PATTERN = /^attempt-(\d+)\.diff(?:\.json)?$/u;
const GIT_DIFF_MAX_BUFFER_BYTES = 64 * 1024 * 1024;
const UNKNOWN_GIT_ERROR = 'unknown error';
const AUTO_DIFF_EMPTY_ERROR =
  'auto-diff: git diff is empty — nothing changed since the step began; ' +
  'make the change first (or pass an explicit --changeRef diff:<path>)';
const AUTO_DIFF_PATH_DISCOVERY_ERROR =
  'auto-diff: working-tree path discovery failed: ';
const AUTO_DIFF_REPORT_DELETION_DISCOVERY_ERROR =
  'auto-diff: report deletion path discovery failed: ';
const AUTO_DIFF_FOREIGN_BOOKKEEPING_NOTICE =
  'auto-diff: excluded another quest\'s bookkeeping from the attempt: ';
const GIT_COMMAND = 'git';
const GIT_OUTPUT_ENCODING = 'utf8';
const LINE_SEPARATOR = '\n';
const PATH_LIST_SEPARATOR = ', ';
const AUTO_DIFF_UNTRACKED_ERROR_PREFIX =
  'auto-diff: untracked source files would be silently omitted from ' +
  'the sealed attempt artifact: ';
const AUTO_DIFF_UNTRACKED_ERROR_SUFFIX =
  ' — run git add -N <file> to include them (or delete them) before ' +
  'committing the step';

// Solver-owned GENERATED bookkeeping the step/loop machinery itself writes
// between step begin and commit: the pending file (solve/state, stepBegin),
// event-log appends (solve/log — gate decisions fire at begin time), the
// content-addressed attempt objects (solve/artifacts), regenerated reports
// (solve/report), the frontier board refresh
// (solve/FRONTIER.generated.md), and the owner inventories refreshed only by
// final landing. Sweeping these into an --auto-diff artifact
// self-poisons a product quest: the change-artifact honesty gate classifies
// solve/ paths as workflow changes and rejects the attempt. Only these
// generated paths are excluded — the operator's INTENTIONAL edits under
// solve/ (quest JSON, epics, specs) are still captured. OTHER quests'
// evidence receipts (solve/evidence/<other>.receipt.json, regenerated by
// their harnesses in the shared worktree) and OTHER quests' bookkeeping
// (their quest file, log, evidence, oracle, changes) are excluded per quest
// id below (isForeignQuestBookkeeping) and named on stdout; this quest's
// own bookkeeping stays captured.
const AUTO_DIFF_EXCLUDED_BOOKKEEPING_PATHSPECS = Object.freeze([
  'solve/FRONTIER.generated.md',
  'solve/artifacts',
  'solve/state',
  'solve/log',
  'solve/report',
  'solve/changes/global-owner-debt-inventory/inventory.json',
  'solve/changes/priority-recovery-owner-inventory/inventory.json',
].map((bookkeepingPath) => `:(exclude)${bookkeepingPath}`));
const REPORT_PROJECTION_PATHSPEC = 'solve/report';
// git diff never sees untracked files, so a brand-new test or script created
// during the attempt silently falls out of the sealed artifact — the exact
// omission an independent verifier must reject (behavior change sealed
// without its regression guard). Guard the source-owning trees; stray
// operator files elsewhere stay irrelevant to the seal.
const AUTO_DIFF_UNTRACKED_GUARD_PATHSPECS = Object.freeze([
  'docs',
  'examples',
  'scripts',
  'src',
  'test',
]);

function nextAutoDiffArtifactPath(root, questId) {
  const dir = expectedChangeDir(root, questId);
  fs.mkdirSync(dir, {recursive: true});
  let next = 1;
  for (const name of fs.readdirSync(dir)) {
    const match = AUTO_DIFF_ARTIFACT_PATTERN.exec(name);
    if (match) next = Math.max(next, Number(match[1]) + 1);
  }
  return path.join(
    dir, `${AUTO_DIFF_ARTIFACT_PREFIX}${next}${AUTO_DIFF_ARTIFACT_EXTENSION}`);
}

function gitCapture(root, args) {
  return spawnSync(GIT_COMMAND, args, {
    cwd: root,
    encoding: GIT_OUTPUT_ENCODING,
    maxBuffer: GIT_DIFF_MAX_BUFFER_BYTES,
  });
}

export function untrackedSourcePaths(root) {
  const untracked = gitCapture(root, [
    'ls-files', '--others', '--exclude-standard', '--',
    ...AUTO_DIFF_UNTRACKED_GUARD_PATHSPECS,
  ]);
  return (untracked.stdout || '')
    .split(LINE_SEPARATOR)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

// Snapshot the working tree (vs `pin`, the base recorded at step begin, else
// HEAD) into solve/changes/<questId>/attempt-<n>.diff and return a changeRef
// descriptor. The resulting artifact goes through the same
// inspectChangeArtifact honesty gate as an operator-provided diff. An empty
// diff is an operator error, not a silent no-op.
export function createAutoDiffChangeRef(root, quest, pin) {
  const untrackedSourceFiles = untrackedSourcePaths(root);
  if (untrackedSourceFiles.length > 0) {
    throw new Error(
      AUTO_DIFF_UNTRACKED_ERROR_PREFIX +
      untrackedSourceFiles.join(PATH_LIST_SEPARATOR) +
      AUTO_DIFF_UNTRACKED_ERROR_SUFFIX,
    );
  }
  // Collateral verification contract (verification.js v3): registered
  // generated outputs are landing collateral regenerated at the landing
  // tree, never reviewed attempt bytes.
  const excludedCollateralPathspecs = questContractExcludesCollateral(quest) ?
    registeredGeneratedOutputPaths()
      .map((outputPath) => `:(exclude)${outputPath}`) :
    [];
  // Discover only current index/worktree changes. The source epoch pin can be
  // older than HEAD after an unrelated commit; discovering paths from that pin
  // would silently sweep the intervening commit into this Quest. Once the
  // authored path set is known, the canonical payload is still rendered from
  // the epoch pin so every attempt retains the one common review base.
  const authored = gitCapture(root, [
    'diff', '--binary', '--full-index', '--no-ext-diff', 'HEAD', '--', '.',
    ...AUTO_DIFF_EXCLUDED_BOOKKEEPING_PATHSPECS,
    ...excludedCollateralPathspecs,
  ]);
  if (authored.status !== 0 || typeof authored.stdout !== 'string') {
    throw new Error(
      AUTO_DIFF_PATH_DISCOVERY_ERROR +
      `${(authored.stderr || UNKNOWN_GIT_ERROR).trim()}`,
    );
  }
  // Report rewrites remain generated bookkeeping, but a deliberate migration
  // that removes tracked projections must be captured exactly. Add only tracked
  // deletions from the report tree; ordinary modifications and regenerated
  // ignored reports stay outside the attempt artifact.
  const removedReports = gitCapture(root, [
    'diff', '--binary', '--full-index', '--no-ext-diff', '--diff-filter=D',
    'HEAD', '--', REPORT_PROJECTION_PATHSPEC,
  ]);
  if (removedReports.status !== 0 || typeof removedReports.stdout !== 'string') {
    throw new Error(
      AUTO_DIFF_REPORT_DELETION_DISCOVERY_ERROR +
      `${(removedReports.stderr || UNKNOWN_GIT_ERROR).trim()}`,
    );
  }
  const discoveredPaths = [...new Set([
    ...changedPathsFromDiffContent(authored.stdout),
    ...changedPathsFromDiffContent(removedReports.stdout),
  ])].sort();
  const foreignBookkeeping = discoveredPaths.filter((filePath) =>
    isForeignQuestBookkeeping(root, filePath, quest.id));
  if (foreignBookkeeping.length > 0) {
    // Never silent: the operator sees exactly which other-quest bookkeeping
    // stayed dirty in the tree and out of this quest's sealed artifact.
    process.stdout.write(
      `${AUTO_DIFF_FOREIGN_BOOKKEEPING_NOTICE}` +
      `${foreignBookkeeping.join(PATH_LIST_SEPARATOR)}${LINE_SEPARATOR}`,
    );
  }
  const changedPaths = discoveredPaths.filter((filePath) =>
    !foreignBookkeeping.includes(filePath));
  if (changedPaths.length === 0) {
    throw new Error(AUTO_DIFF_EMPTY_ERROR);
  }
  // Re-diff the exact union once so the persisted payload has Git's canonical
  // ordering. Concatenating individually valid diffs is not a canonical source
  // artifact when their path ranges interleave.
  const canonical = gitCapture(root, [
    'diff', '--binary', '--full-index', '--no-ext-diff', pin, '--',
    ...changedPaths,
  ]);
  if (canonical.status !== 0 || typeof canonical.stdout !== 'string') {
    throw new Error(
      `auto-diff: canonical Git delta ${pin} failed: ` +
      `${(canonical.stderr || UNKNOWN_GIT_ERROR).trim()}`,
    );
  }
  const file = nextAutoDiffArtifactPath(root, quest.id);
  const relativeFile = path.relative(root, file);
  return writeContentAddressedChangeArtifact(
    root,
    relativeFile,
    canonical.stdout,
  );
}
