// Preflight — batch, read-only landing diagnostics for one quest.
//
// Before this verb the operator discovered landing blockers one at a time:
// `land` stopped at the first refused gate (union guard, then commit gate,
// then audit), each discovery costing a full landing run and sometimes an
// override. Preflight runs every landing-facing diagnostic in one pass,
// writes NO log event, consumes NO override, and reports every problem
// grouped by section, so one invocation shows the full repair surface.
//
// Preflight is NOT the pre-commit hook: the hook additionally runs the
// hot-path diagnostics, staged constant-name, decision-boundary,
// ambient-intrinsics, silent-catch, documentation ASCII, and inventory
// regeneration checks over the exact staged set. A green preflight means
// the landing machinery has no standing refusal, not that every staged
// byte passes the commit hook.

import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

import {auditQuest} from './audit.js';
import {readLog} from './store.js';
import {untrackedSourcePaths} from './auto-diff.js';
import {fileSizeAdmissionProblems} from './file-size-admission.js';
import {
  generatedOutputCoverage,
  registeredGeneratedOutputPaths,
} from './generated-dependencies.js';
import {
  landingUnionGuardProblems,
  workingSourceDelta,
} from './landing-union-guard.js';
import {requiredReviewTemplates} from './review-request.js';
import {
  questContractExcludesCollateral,
  verificationState,
} from './verification.js';
import {GENERATED_OUTPUT_COVERAGE} from './constants.js';

const SECTION_AUDIT = 'audit';
const SECTION_UNION = 'landing-union';
const SECTION_UNTRACKED = 'untracked-intent';
const SECTION_GENERATED = 'generated-outputs';
const SECTION_FILE_SIZE = 'file-size';
const SECTION_TEMPLATES = 'review-templates';
const SECTION_PUBLISH_STATIC = 'publish-static';
const FULL_FLAG = 'full';
const PUBLISH_STATIC_SKIPPED_NOTE =
  'publish statics not run: pass --full to run the duplication, unused-export, ' +
  'circular-dependency, and complexity ratchets the publish gate enforces';
const PUBLISH_STATIC_OUTPUT_LINE_LIMIT = 12;
const PUBLISH_STATIC_MAX_BUFFER_BYTES = 16 * 1024 * 1024;
const PUBLISH_STATIC_CHECKS = Object.freeze([
  Object.freeze({label: 'duplication ratchet',
    segments: ['scripts', 'check-duplication.js']}),
  Object.freeze({label: 'unused-export ratchet',
    segments: ['scripts', 'check-unused-exports.js']}),
  Object.freeze({label: 'circular-dependency ratchet',
    segments: ['scripts', 'check-circular-dependencies.js']}),
  Object.freeze({label: 'complexity ratchet',
    segments: ['scripts', 'check-complexity.js']}),
  Object.freeze({label: 'cognitive complexity ratchet',
    segments: ['scripts', 'check-cognitive-complexity.js']}),
]);
const HEAD_BASE = 'HEAD';
const LINE_SEPARATOR = '\n';
const SECTION_PROBLEM_SUFFIX = ' problem(s)';
const SECTION_CLEAN = 'clean';
const SECTION_HEADER_PREFIX = '## ';
const PROBLEM_LINE_PREFIX = '- ';
const UNTRACKED_PROBLEM_PREFIX =
  'untracked source file would be invisible to the sealed attempt and the ' +
  'landing delta: ';
const UNTRACKED_PROBLEM_SUFFIX = ' — stage intent with git add -N';
const GENERATED_STALE_PREFIX = 'registered generated output not covered: ';
const GENERATED_REASON_OPEN = ' (';
const GENERATED_REASON_CLOSE = ')';
const COLLATERAL_NOTE =
  'collateral contract: registered generated outputs are regenerated by ' +
  'the landing itself and never block';
const TEMPLATE_REQUIRED_PREFIX = 'required verification template: ';
const TEMPLATE_SOURCE_OPEN = ' [';
const TEMPLATE_SOURCE_CLOSE = ']';
const TEMPLATE_SOURCE_SEPARATOR = ', ';
const REPORT_TITLE_PREFIX = 'preflight: ';
const REPORT_STATUS_GREEN = 'no standing landing refusal';
const REPORT_STATUS_RED = ' problem(s) across ';
const REPORT_STATUS_SECTIONS = ' section(s)';
const PREFLIGHT_ID_REQUIRED = 'preflight: --id <questId> is required';

function auditProblemMessages(root, quest) {
  const audit = auditQuest(root, quest);
  return (audit.problems || []).map((problem) =>
    typeof problem === 'string' ? problem : problem.message);
}

function unionProblemMessages(root, quest, log) {
  return landingUnionGuardProblems(root, quest, log)
    .map((problem) => problem.message);
}

function untrackedProblemMessages(root) {
  return untrackedSourcePaths(root).map((filePath) =>
    UNTRACKED_PROBLEM_PREFIX + filePath + UNTRACKED_PROBLEM_SUFFIX);
}

// Every registered output is evaluated and every stale/unavailable one is
// reported together — unlike the receipt path, which throws on the first.
// Under the collateral contract the landing regenerates the outputs itself,
// so staleness is informational-only and never a problem.
function generatedOutputProblemMessages(root, quest, log) {
  if (questContractExcludesCollateral(quest)) return {problems: [], notes: [COLLATERAL_NOTE]};
  const aggregate = verificationState(root, quest, log).aggregate;
  const dirty = workingSourceDelta(root).paths;
  const registered = registeredGeneratedOutputPaths()
    .filter((outputPath) => dirty.includes(outputPath));
  if (registered.length === 0) return {problems: [], notes: []};
  const entries = generatedOutputCoverage(root, aggregate, registered);
  const problems = entries
    .filter((entry) => entry.coverage !== GENERATED_OUTPUT_COVERAGE.FRESH)
    .map((entry) => GENERATED_STALE_PREFIX + entry.path +
      GENERATED_REASON_OPEN + entry.reason + GENERATED_REASON_CLOSE);
  return {problems, notes: []};
}

// The publish-gate statics no Solver stage runs before the push (measured
// 2026-09-04/05: complexity, duplication, and unused-export misses each cost
// a 13-25 minute gate run). Whole-repo and slow (~2 min), so opt-in.
function publishStaticProblemMessages(root) {
  const problems = [];
  for (const check of PUBLISH_STATIC_CHECKS) {
    const script = path.join(root, ...check.segments);
    if (!fs.existsSync(script)) continue;
    const result = spawnSync(process.execPath, [script], {cwd: root,
      encoding: 'utf8', maxBuffer: PUBLISH_STATIC_MAX_BUFFER_BYTES});
    if (result.error) {
      problems.push(`${check.label} could not run: ${result.error.message}`);
      continue;
    }
    if (result.status === 0) continue;
    const lines = `${result.stdout || ''}${LINE_SEPARATOR}${result.stderr || ''}`
      .split(LINE_SEPARATOR).map((line) => line.trimEnd()).filter(Boolean);
    const shown = lines.slice(-PUBLISH_STATIC_OUTPUT_LINE_LIMIT);
    problems.push(`${check.label} failed:${LINE_SEPARATOR}` +
      shown.join(LINE_SEPARATOR));
  }
  return problems;
}

function fileSizeProblemMessages(root) {
  const dirty = workingSourceDelta(root).paths;
  if (dirty.length === 0) return [];
  return fileSizeAdmissionProblems(root, HEAD_BASE, dirty);
}

// Informational: the categories a review of the current candidate will
// require. Evidence filenames are not a contract (verdict ingestion accepts
// arbitrary evidencePaths), so preflight names the obligation and never
// guesses at file names.
function templateNotes(root, quest, log) {
  const state = verificationState(root, quest, log);
  return requiredReviewTemplates(root, quest, state, log)
    .map((template) => TEMPLATE_REQUIRED_PREFIX + template.category +
      TEMPLATE_SOURCE_OPEN +
      template.sources.join(TEMPLATE_SOURCE_SEPARATOR) +
      TEMPLATE_SOURCE_CLOSE);
}

export function preflightReport(root, quest, options = {}) {
  const log = readLog(root, quest.id);
  const generated = generatedOutputProblemMessages(root, quest, log);
  const publishStatic = options.full ?
    {problems: publishStaticProblemMessages(root), notes: []} :
    {problems: [], notes: [PUBLISH_STATIC_SKIPPED_NOTE]};
  const sections = [
    {name: SECTION_AUDIT, problems: auditProblemMessages(root, quest),
      notes: []},
    {name: SECTION_UNION, problems: unionProblemMessages(root, quest, log),
      notes: []},
    {name: SECTION_UNTRACKED, problems: untrackedProblemMessages(root),
      notes: []},
    {name: SECTION_GENERATED, problems: generated.problems,
      notes: generated.notes},
    {name: SECTION_FILE_SIZE, problems: fileSizeProblemMessages(root),
      notes: []},
    {name: SECTION_TEMPLATES, problems: [],
      notes: templateNotes(root, quest, log)},
    {name: SECTION_PUBLISH_STATIC, problems: publishStatic.problems,
      notes: publishStatic.notes},
  ];
  const problemCount = sections
    .reduce((count, section) => count + section.problems.length, 0);
  return {ok: problemCount === 0, problemCount, sections};
}

function renderSection(section) {
  const status = section.problems.length > 0 ?
    section.problems.length + SECTION_PROBLEM_SUFFIX : SECTION_CLEAN;
  const lines = [SECTION_HEADER_PREFIX + section.name + ': ' + status];
  for (const problem of section.problems) {
    lines.push(PROBLEM_LINE_PREFIX + problem);
  }
  for (const note of section.notes) {
    lines.push(PROBLEM_LINE_PREFIX + note);
  }
  return lines;
}

export function renderPreflightReport(quest, report) {
  const redSections = report.sections
    .filter((section) => section.problems.length > 0).length;
  const headline = report.ok ?
    REPORT_TITLE_PREFIX + quest.id + ': ' + REPORT_STATUS_GREEN :
    REPORT_TITLE_PREFIX + quest.id + ': ' + report.problemCount +
      REPORT_STATUS_RED + redSections + REPORT_STATUS_SECTIONS;
  const lines = [headline];
  for (const section of report.sections) {
    lines.push(...renderSection(section));
  }
  return lines.join(LINE_SEPARATOR) + LINE_SEPARATOR;
}

export function runPreflightCommand(root, args, loadQuest) {
  const id = args.id || args._[0];
  if (!id) throw new Error(PREFLIGHT_ID_REQUIRED);
  const quest = loadQuest(root, id);
  const report = preflightReport(root, quest, {full: args[FULL_FLAG] === true});
  return {output: renderPreflightReport(quest, report), ok: report.ok};
}
